<x-layouts.app :title="$session->name">
 <div x-data="{state:'{{ $session->status->value }}',label:'{{ $session->status->label() }}',polls:0,qrBase:@js(route('tenant.whatsapp.qr', $session->uuid)),qrUrl:@js($session->status->value === 'qr_pending' ? route('tenant.whatsapp.qr', $session->uuid).'?v='.$session->qr_generation_count : '')}" x-init="if(['creating','initializing','qr_pending','authenticating','authenticated','reconnecting'].includes(state)){let timer=setInterval(async()=>{if(document.hidden)return;try{let r=await fetch('{{ route('tenant.whatsapp.status',$session->uuid) }}',{headers:{Accept:'application/json'}});if(!r.ok)throw 0;let d=await r.json();state=d.status;label=d.status_label;if(d.qr_available){let next=qrBase+'?v='+d.qr_generation_count;if(qrUrl!==next)qrUrl=next}else if(state==='qr_pending'){qrUrl=''}polls++;if(!d.next_poll_after_ms||polls>100)clearInterval(timer)}catch(e){if(++polls>8)clearInterval(timer)}},3000)}">
  <x-page-header eyebrow="Linked device" :title="$session->name" description="Secure WhatsApp Web authentication and connection health."><x-slot:actions><a class="btn-secondary" href="{{ route('tenant.whatsapp.index') }}">All sessions</a></x-slot:actions></x-page-header>
  <div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
   <div class="space-y-6">
    <section class="panel" aria-live="polite"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p class="eyebrow">Connection state</p><h2 class="mt-2 text-2xl font-semibold" x-text="label">{{ $session->status->label() }}</h2><p class="muted mt-2">Last updated {{ $session->updated_at->diffForHumans() }}</p></div><x-badge :variant="$session->status->value==='ready'?'success':($session->status->value==='failed'?'danger':'info')"><span x-text="label">{{ $session->status->label() }}</span></x-badge></div>
     @if($session->status->value==='ready')<div class="mt-6 grid gap-4 sm:grid-cols-2"><div class="app-card-subtle p-4"><p class="muted">Connected account</p><p class="mt-1 font-semibold">{{ $session->display_name ?: 'WhatsApp account' }}</p><p class="text-sm text-[var(--text-muted)]">{{ $session->phone_number }}</p></div><div class="app-card-subtle p-4"><p class="muted">Ready since</p><p class="mt-1 font-semibold">{{ $session->ready_at?->format('M j, Y H:i') }}</p></div></div>@endif
     @if($session->status->value==='failed')<x-alert variant="danger" class="mt-5">{{ $session->failure_message ?: 'The connector could not initialize this session. Retry safely or contact support.' }}</x-alert>@endif
    </section>
    <section class="panel" x-cloak x-show="state==='qr_pending'"><div class="grid items-center gap-7 md:grid-cols-[280px_1fr]"><div class="flex aspect-square items-center justify-center rounded-2xl border bg-white p-4 shadow-sm"><img x-show="qrUrl" :src="qrUrl" alt="WhatsApp linked-device QR code" class="aspect-square w-full" width="248" height="248"><div x-show="!qrUrl" class="px-5 text-center text-sm text-slate-600"><span class="mx-auto mb-3 block size-6 animate-spin rounded-full border-2 border-slate-400 border-r-transparent"></span>Waiting for a fresh QR code…</div></div><div><p class="eyebrow">Scan with your phone</p><h2 class="section-title mt-2">Link this device</h2><ol class="mt-4 space-y-3 text-sm text-[var(--text-secondary)]"><li><b>1.</b> Open WhatsApp on your phone.</li><li><b>2.</b> Open Settings or Menu, then Linked Devices.</li><li><b>3.</b> Choose Link a Device and scan this code.</li><li><b>4.</b> Keep this page open while authentication completes.</li></ol><p class="muted mt-5">QR codes expire and refresh automatically. Never share this code.</p></div></div></section>
    <section class="panel" x-cloak x-show="['creating','initializing','authenticating','authenticated','reconnecting'].includes(state)"><div class="flex items-center gap-4"><span class="size-6 animate-spin rounded-full border-2 border-[var(--accent)] border-r-transparent" aria-hidden="true"></span><div><h2 class="section-title">Connection in progress</h2><p class="muted">Browser initialization and WhatsApp authentication can take a little while. This page updates automatically.</p></div></div></section>
    <section class="panel"><h2 class="section-title">Connection history</h2><div class="mt-4 space-y-4">@forelse($session->events as $event)<article class="border-l-2 border-[var(--accent-soft)] pl-4"><div class="flex justify-between gap-3"><b class="text-sm">{{ str($event->event)->replace('.',' ')->headline() }}</b><time class="text-xs text-[var(--text-muted)]">{{ $event->occurred_at->diffForHumans() }}</time></div><p class="muted">{{ $event->message ?: str($event->to_status)->replace('_',' ')->headline() }}</p></article>@empty<p class="muted">Lifecycle events will appear here.</p>@endforelse</div></section>
   </div>
   <aside class="space-y-6"><section class="panel"><h2 class="section-title">Session actions</h2><div class="mt-4 space-y-3">@if(in_array($session->status->value,['ready','disconnected','failed']))<form method="post" action="{{ route('tenant.whatsapp.reconnect',$session->uuid) }}">@csrf<button class="btn-primary w-full">Reconnect session</button></form>@endif @if($session->status->value==='ready')<form method="post" action="{{ route('tenant.whatsapp.disconnect',$session->uuid) }}">@csrf<button class="btn-secondary w-full">Disconnect safely</button></form>@endif<form method="post" action="{{ route('tenant.whatsapp.destroy',$session->uuid) }}" onsubmit="return confirm('Delete this session and its connector authentication data?')">@csrf @method('delete')<button class="btn-danger w-full">Delete session</button></form></div><p class="muted mt-4">Disconnect preserves authentication for reconnect. Delete requests permanent connector cleanup.</p></section><section class="app-card-subtle p-5"><p class="eyebrow">Responsible use</p><p class="muted mt-2">WhatsApp Web behavior can change without notice. Use only authorized accounts and follow WhatsApp policies.</p></section></aside>
  </div>
 </div>
</x-layouts.app>
