<section class="card my-5">
    <h2 class="font-semibold">Execution</h2><p class="mt-1 text-sm text-slate-400">Consent, opt-out, suppression, campaign integrity, session health, subscription access, and usage are checked again before dispatch.</p>
    @if(in_array('launch',$statusPresentation['actions']))<form class="mt-4" method="post" action="{{ route('tenant.campaigns.launch',$campaign) }}" onsubmit="return confirm('Launch this prepared recipient snapshot through the selected WhatsApp sessions?')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-primary">Launch campaign</button></form>@endif
    @if($execution=$campaign->activeExecution)
        <div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach(['Status'=>$execution->status->value,'Progress'=>$execution->progress_percentage.'%','Pending'=>$execution->pending_recipients,'Processing'=>$execution->processing_recipients,'Retry scheduled'=>$execution->retry_scheduled_recipients,'Transport pending'=>$execution->transport_pending_recipients,'Unknown'=>$execution->unknown_recipients,'Sent'=>$execution->sent_recipients,'Delivered'=>$execution->delivered_recipients,'Read'=>$execution->read_recipients,'Failed'=>$execution->failed_recipients,'Cancelled'=>$execution->cancelled_recipients] as $label=>$value)<div><span class="text-xs text-slate-500">{{ $label }}</span><p>{{ $value }}</p></div>@endforeach</div>
        <div class="mt-4 flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('tenant.campaigns.execution',$campaign) }}">Execution details</a>
            @if(in_array('pause',$statusPresentation['actions']))<form method="post" action="{{ route('tenant.campaigns.pause',$campaign) }}" onsubmit="return confirm('Pausing stops new recipients from being claimed. Work already in progress may finish before the campaign becomes fully paused.')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-secondary">Pause</button></form>@endif
            @if(in_array('resume',$statusPresentation['actions']))<form method="post" action="{{ route('tenant.campaigns.resume',$campaign) }}" onsubmit="return confirm('Eligibility, sessions, campaign integrity, subscription access, and usage will be checked again.')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-primary">Resume</button></form>@endif
            @if(in_array('cancel',$statusPresentation['actions']))<form method="post" action="{{ route('tenant.campaigns.execution.cancel',$campaign) }}" onsubmit="return confirm('Unsent recipients will be cancelled. Messages already confirmed as sent cannot be recalled.')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-secondary">Cancel</button></form>@endif
        </div>
    @endif
</section>
