@php($campaign->setRelation('activePreparation', $currentPreparation))
<section class="card my-5">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 class="font-semibold">Recipient preparation</h2><p class="mt-1 text-sm text-slate-400">Preparation creates the fixed recipient snapshot. It does not send messages.</p></div><form x-data="{estimate:null,loading:false}" @submit.prevent="loading=true; fetch($el.action,{method:'POST',headers:{'X-CSRF-TOKEN':@js(csrf_token()),Accept:'application/json'}}).then(r=>r.json()).then(v=>estimate=v).finally(()=>loading=false)" method="post" action="{{ route('tenant.campaigns.audience-estimate',$campaign) }}"><button class="btn-secondary" x-text="loading?'Calculating…':'Recalculate estimate'"></button><p x-show="estimate" class="mt-2 text-xs text-slate-400"><span x-text="estimate?.candidate_count"></span> candidates · <span x-text="estimate?.estimated_eligible_count"></span> estimated eligible</p></form></div>
    @if($p=$campaign->activePreparation)
        <div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach(['Status'=>$p->status->value,'Progress'=>$p->progress_percentage.'%','Candidates'=>$p->total_candidates,'Processed'=>$p->processed_candidates,'Eligible'=>$p->eligible_count,'Excluded'=>$p->excluded_count,'Duplicates'=>$p->duplicate_count,'Invalid'=>$p->invalid_count] as $label=>$value)<div><span class="text-xs text-slate-500">{{ $label }}</span><p>{{ $value }}</p></div>@endforeach</div>
        @if($p->failure_code)<x-alert class="mt-4" variant="danger">{{ $p->failure_message ?: str($p->failure_code)->replace('_',' ')->headline() }}</x-alert>@endif
        <div class="mt-4 flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('tenant.campaigns.recipients',$campaign) }}">View recipients</a><a class="btn-secondary" href="{{ route('tenant.campaigns.exclusions',$campaign) }}">View exclusions</a>
            @if($campaign->status->value==='preparing')<form method="post" action="{{ route('tenant.campaigns.preparation.cancel',$campaign) }}" onsubmit="return confirm('Cancel recipient preparation? No messages have been sent.')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-secondary">Cancel preparation</button></form>@endif
            @if($campaign->status->value==='prepared')<form method="post" action="{{ route('tenant.campaigns.preparation.invalidate',$campaign) }}" onsubmit="return confirm('Invalidate this fixed snapshot before editing the campaign?')">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-secondary">Invalidate snapshot</button></form>@endif
        </div>
    @endif
    @if(in_array('prepare',$statusPresentation['actions']))<form class="mt-5" method="post" action="{{ route('tenant.campaigns.prepare',$campaign) }}">@csrf<input type="hidden" name="expected_version" value="{{ $campaign->version }}"><input type="hidden" name="idempotency_token" value="{{ \Illuminate\Support\Str::uuid() }}"><button class="btn-primary">Prepare recipients</button></form>@endif
</section>
