<x-layouts.app :title="isset($campaign) ? 'Edit campaign' : 'New campaign'">
    @php($selectedAudience=old('audience_config',isset($campaign)?$campaign->audienceReferences->pluck('reference_uuid')->all():[]))
    @php($selectedSessions=old('session_uuids',isset($campaign)?$campaign->sessionSelections->pluck('session.uuid')->filter()->all():[]))
    <x-page-header :title="isset($campaign) ? 'Edit campaign' : 'Create campaign draft'" description="Configure content, consent-aware recipients, sessions, and launch timing."/>
    @if($errors->any())<x-alert variant="danger" title="Campaign could not be saved"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
    <form x-data="{step:1,type:'{{ old('message_type',$campaign->message_type->value??'text') }}',audience:'{{ old('audience_type',$campaign->audience_type->value??'all_eligible_contacts') }}',schedule:'{{ old('schedule_type',$campaign->schedule_type->value??'send_now') }}',body:@js(old('body',$campaign->body??''))}" method="post" enctype="multipart/form-data" action="{{ isset($campaign)?route('tenant.campaigns.update',$campaign):route('tenant.campaigns.store') }}">
        @csrf @isset($campaign)@method('PUT')<input type="hidden" name="expected_version" value="{{ $campaign->version }}">@endisset
        <input type="hidden" name="idempotency_key" value="{{ old('idempotency_key',(string)\Illuminate\Support\Str::uuid()) }}">
        <nav class="mb-5 flex gap-2 overflow-x-auto pb-2" aria-label="Campaign form steps">
            @foreach(['Basics','Message','Audience','Sessions','Schedule','Review'] as $number=>$label)<button type="button" class="btn-secondary shrink-0" :class="step=={{ $number+1 }} && 'ring-2 ring-emerald-500'" @click="step={{ $number+1 }}" :aria-current="step=={{ $number+1 }} ? 'step' : null">{{ $number+1 }}. {{ $label }}</button>@endforeach
        </nav>
        <section x-show="step===1" class="card grid gap-4 md:grid-cols-2"><label>Campaign name<input class="input mt-2" name="name" required maxlength="150" value="{{ old('name',$campaign->name??'') }}"></label><label>Internal description<textarea class="input mt-2" name="description">{{ old('description',$campaign->description??'') }}</textarea></label></section>
        <section x-show="step===2" class="card grid gap-5 lg:grid-cols-2">
            @isset($campaign)<div class="lg:col-span-2 rounded-xl border p-4" x-data="{template:'',busy:false,error:''}"><h2 class="font-semibold">Published message template</h2><p class="mt-1 text-xs text-[var(--text-muted)]">Only current published templates are selectable. Applying freezes template and version metadata.</p><div class="mt-3 flex flex-col gap-2 sm:flex-row"><select class="input flex-1" x-model="template"><option value="">Select a published template</option>@foreach($messageTemplates as $messageTemplate)<option value="{{ $messageTemplate->uuid }}">{{ $messageTemplate->name }} · {{ ucfirst($messageTemplate->type->value) }} · v{{ $messageTemplate->currentPublishedVersion->version_number }}</option>@endforeach</select><button type="button" class="btn-secondary" :disabled="!template||busy" @click="busy=true;fetch('{{ route('tenant.campaigns.template.apply',$campaign) }}',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({template_uuid:template,expected_version:{{ $campaign->version }},values:{}})}).then(r=>{if(!r.ok)throw Error();location.reload()}).catch(()=>error='Template could not be applied.').finally(()=>busy=false)">Apply template</button></div>@if($campaign->template_uuid)<p class="mt-3 text-sm">Applied version: v{{ $campaign->template_version_number }} · {{ $campaign->template_version_uuid }}</p><button type="button" class="btn-secondary mt-2" @click="fetch('{{ route('tenant.campaigns.template.detach',$campaign) }}',{method:'DELETE',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({expected_version:{{ $campaign->version }}})}).then(r=>{if(!r.ok)throw Error();location.reload()}).catch(()=>error='Template could not be detached.')">Detach and preserve content</button>@endif<p class="mt-2 text-sm text-red-500" x-text="error" role="alert"></p></div>@endisset
            <div class="space-y-4"><label>Message type<select class="input mt-2" name="message_type" x-model="type">@foreach(\App\Enums\WhatsAppMessageType::cases() as $t)<option value="{{ $t->value }}">{{ ucfirst($t->value) }}</option>@endforeach</select></label><label x-show="type!=='text'">Private attachment<input class="input mt-2" type="file" name="attachment" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,audio/mpeg,audio/ogg,video/mp4"></label>@isset($campaign)@if($campaign->attachment)<p class="text-sm text-slate-400">Current: {{ $campaign->attachment->safe_name }} · {{ number_format($campaign->attachment->size_bytes/1024,1) }} KB</p>@endif@endisset<label>Message body or caption<textarea class="input mt-2 min-h-36" name="body" maxlength="4096" x-model="body"></textarea><span class="text-xs text-slate-500" x-text="body.length + ' / 4096 characters'"></span></label></div>
            <aside class="rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 class="font-semibold">Preview</h2><div class="mt-4 max-w-sm rounded-2xl rounded-tr-sm bg-emerald-950 p-4"><p class="text-xs text-emerald-300" x-text="type.toUpperCase()"></p><p class="mt-2 whitespace-pre-wrap" x-text="body || 'Your message preview appears here.'"></p></div></aside>
        </section>
        <section x-show="step===3" class="card grid gap-4 md:grid-cols-2">
            <label>Audience source<select class="input mt-2" name="audience_type" x-model="audience">@foreach(\App\Enums\WhatsAppCampaignAudienceType::cases() as $t)<option value="{{ $t->value }}">{{ str($t->value)->replace('_',' ')->headline() }}</option>@endforeach</select></label>
            <label x-show="audience!=='all_eligible_contacts'">Saved audience entries<select class="input mt-2 min-h-44" name="audience_config[]" multiple>@foreach($segments as $x)<option value="{{ $x->uuid }}" @selected(in_array($x->uuid,$selectedAudience))>Segment: {{ $x->name }}</option>@endforeach @foreach($groups as $x)<option value="{{ $x->uuid }}" @selected(in_array($x->uuid,$selectedAudience))>Group: {{ $x->name }}</option>@endforeach @foreach($labels as $x)<option value="{{ $x->uuid }}" @selected(in_array($x->uuid,$selectedAudience))>Label: {{ $x->name }}</option>@endforeach @foreach($contacts as $x)<option value="{{ $x->uuid }}" @selected(in_array($x->uuid,$selectedAudience))>Contact: {{ $x->display_name ?: $x->maskedPhone() }} · {{ $x->maskedPhone() }}</option>@endforeach</select><span class="text-xs text-slate-500">Only saved tenant contacts are selectable. Raw phone entry is unavailable.</span></label>
            <div class="md:col-span-2 rounded-xl border border-slate-700 p-4 text-sm text-slate-300">Eligibility, consent, opt-out, suppression, and blocks are enforced during preparation and rechecked before dispatch. This estimate may change before recipient preparation.</div>
        </section>
        <section x-show="step===4" class="card grid gap-4 md:grid-cols-2"><label>Session strategy<select class="input mt-2" name="session_strategy">@foreach(\App\Enums\WhatsAppCampaignSessionStrategy::cases() as $t)<option value="{{ $t->value }}" @selected(old('session_strategy',$campaign->session_strategy->value??'automatic_pool')===$t->value)>{{ str($t->value)->replace('_',' ')->headline() }}</option>@endforeach</select></label><label>Available tenant sessions<select class="input mt-2 min-h-36" name="session_uuids[]" multiple>@foreach($sessions as $s)<option value="{{ $s->uuid }}" @selected(in_array($s->uuid,$selectedSessions)) @disabled($s->status->value!=='ready')>{{ $s->name }} · {{ $s->status->label() }} · {{ $s->last_seen_at?->diffForHumans() ?? 'no heartbeat' }}</option>@endforeach</select></label></section>
        <section x-show="step===5" class="card grid gap-4 md:grid-cols-3"><label>Launch timing<select class="input mt-2" name="schedule_type" x-model="schedule"><option value="send_now">Manual launch</option><option value="scheduled">Scheduled</option></select></label><label x-show="schedule==='scheduled'">Local date/time<input class="input mt-2" type="datetime-local" name="scheduled_at_local" value="{{ old('scheduled_at_local',$campaign->scheduled_at_local??'') }}"></label><label x-show="schedule==='scheduled'">Tenant timezone<input class="input mt-2" name="timezone" value="{{ old('timezone',$campaign->timezone??config('whatsapp_campaigns.default_timezone')) }}"></label></section>
        <section x-show="step===6" class="card space-y-4"><h2 class="font-semibold">Review</h2><dl class="grid gap-3 sm:grid-cols-2"><div><dt class="text-slate-500">Message</dt><dd x-text="type"></dd></div><div><dt class="text-slate-500">Audience</dt><dd x-text="audience.replaceAll('_',' ')"></dd></div><div><dt class="text-slate-500">Schedule</dt><dd x-text="schedule==='scheduled'?'Scheduled launch':'Manual launch'"></dd></div><div><dt class="text-slate-500">Safety</dt><dd>Current consent and opt-out enforcement enabled</dd></div></dl><div class="rounded-xl border border-amber-700/50 bg-amber-950/30 p-4 text-sm text-amber-100">WhatsApp Web sessions may disconnect or be restricted. Acknowledgements may be delayed or unavailable. Your workspace remains responsible for lawful processing and consent.</div><button class="btn-primary">Save draft</button></section>
        <input type="hidden" name="execution[max_attempts_per_recipient]" value="2"><input type="hidden" name="execution[stop_on_session_disconnect]" value="1"><input type="hidden" name="execution[continue_on_recipient_failure]" value="1"><input type="hidden" name="execution[require_current_consent_at_send_time]" value="1">
        <div class="mt-5 flex justify-between"><button x-show="step>1" type="button" class="btn-secondary" @click="step--">Previous</button><button x-show="step<6" type="button" class="btn-primary ml-auto" @click="step++">Continue</button></div>
    </form>
</x-layouts.app>
