<x-layouts.app title="Team">
    <x-page-header eyebrow="Workspace access" title="Team members" description="Manage roles and access without affecting anyone’s other workspaces."><x-slot:actions>@can('create',App\Models\Invitation::class)<a class="btn-primary" href="{{ route('tenant.team.invitations.index') }}">Invite teammate</a>@endcan</x-slot:actions></x-page-header>
    @if($errors->any())<x-alert class="mt-6" variant="danger">{{ $errors->first() }}</x-alert>@endif
    <section class="mt-7 grid grid-cols-2 gap-3 lg:grid-cols-4" aria-label="Member counts">@foreach(['active'=>'success','suspended'=>'warning','removed'=>'neutral','invited'=>'info'] as $state=>$tone)<article class="app-card p-4 sm:p-5"><div class="flex items-center justify-between"><p class="text-sm capitalize text-[var(--text-secondary)]">{{ $state }}</p><x-badge :variant="$tone">{{ $state }}</x-badge></div><p class="metric-value mt-4">{{ $counts[$state] ?? 0 }}</p></article>@endforeach</section>
    <form class="mt-6 grid gap-3 sm:grid-cols-[minmax(0,1fr)_220px_auto]" method="get"><label class="sr-only" for="member-search">Search members</label><input id="member-search" class="field" name="search" value="{{ request('search') }}" placeholder="Search name or email"><label class="sr-only" for="member-status">Member status</label><select id="member-status" class="field" name="status"><option value="">All statuses</option>@foreach(App\Enums\MembershipStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select><x-button type="submit" variant="secondary">Filter</x-button></form>
    <div class="table-shell mt-5">
        @if($members->isEmpty())<x-empty-state title="No matching members" description="Adjust your search or status filter to see more of your team." />
        @else
        <div class="hidden overflow-x-auto lg:block"><table class="data-table"><thead><tr><th>Member</th><th>Role</th><th>Status</th><th>Joined</th><th class="text-right">Actions</th></tr></thead><tbody>@foreach($members as $member)<tr><td><div class="flex items-center gap-3"><span class="grid size-9 place-items-center rounded-xl bg-[var(--accent-soft)] text-xs font-bold text-[var(--accent)]">{{ str($member->user->name)->substr(0,1)->upper() }}</span><span class="min-w-0"><span class="block truncate font-medium">{{ $member->user->name }} @if($member->role->slug==='owner')<x-badge variant="warning">Owner</x-badge>@endif @if($member->user_id===auth()->id())<x-badge>You</x-badge>@endif</span><span class="block truncate text-xs text-[var(--text-muted)]">{{ $member->user->email }}</span></span></div></td><td>{{ $member->role->name }}</td><td><x-badge :variant="$member->status->badgeClass()==='danger'?'danger':($member->status->badgeClass()==='warning'?'warning':($member->status->badgeClass()==='success'?'success':'neutral'))">{{ $member->status->label() }}</x-badge></td><td class="whitespace-nowrap text-[var(--text-muted)]">{{ $member->joined_at?->format('M j, Y') ?? '—' }}</td><td><div class="flex justify-end gap-2">@can('updateRole',$member)<form class="flex gap-2" method="post" action="{{ route('tenant.team.members.role.update',$member->uuid) }}">@csrf @method('PUT')<select class="field min-h-9 w-36 py-1" name="role_id" aria-label="Role for {{ $member->user->name }}">@foreach($roles as $role)<option value="{{ $role->id }}" @selected($member->role_id===$role->id)>{{ $role->name }}</option>@endforeach</select><button class="btn-ghost min-h-9 px-3">Save</button></form>@endcan @if($member->status===App\Enums\MembershipStatus::Active)@can('suspend',$member)<button class="btn-ghost min-h-9 px-3 text-[var(--warning)]" onclick="document.getElementById('suspend-{{ $member->uuid }}').showModal()">Suspend</button>@endcan @elseif($member->status===App\Enums\MembershipStatus::Suspended)@can('reactivate',$member)<button class="btn-ghost min-h-9 px-3" onclick="document.getElementById('reactivate-{{ $member->uuid }}').showModal()">Reactivate</button>@endcan @endif @can('remove',$member)<button class="btn-ghost min-h-9 px-3 text-[var(--danger)]" onclick="document.getElementById('remove-{{ $member->uuid }}').showModal()">Remove</button>@endcan</div></td></tr>@endforeach</tbody></table></div>
        <div class="divide-y lg:hidden">@foreach($members as $member)<article class="p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="truncate font-medium">{{ $member->user->name }} @if($member->user_id===auth()->id())<x-badge>You</x-badge>@endif</p><p class="truncate text-sm text-[var(--text-muted)]">{{ $member->user->email }}</p></div><x-badge :variant="$member->status->isActive()?'success':'neutral'">{{ $member->status->label() }}</x-badge></div><div class="mt-4 flex items-center justify-between border-t pt-3"><span class="text-sm text-[var(--text-secondary)]">{{ $member->role->name }}</span><span class="text-xs text-[var(--text-muted)]">{{ $member->joined_at?->format('M j, Y') ?? 'Not joined' }}</span></div><div class="mt-3 flex flex-wrap gap-2">@if($member->status===App\Enums\MembershipStatus::Active)@can('suspend',$member)<button class="btn-secondary min-h-9" onclick="document.getElementById('suspend-{{ $member->uuid }}').showModal()">Suspend</button>@endcan @elseif($member->status===App\Enums\MembershipStatus::Suspended)@can('reactivate',$member)<button class="btn-secondary min-h-9" onclick="document.getElementById('reactivate-{{ $member->uuid }}').showModal()">Reactivate</button>@endcan @endif @can('remove',$member)<button class="btn-ghost min-h-9 text-[var(--danger)]" onclick="document.getElementById('remove-{{ $member->uuid }}').showModal()">Remove</button>@endcan</div></article>@endforeach</div>
        @endif
    </div><div class="mt-5">{{ $members->links() }}</div>
    @foreach($members as $member)
        @can('suspend',$member)<dialog id="suspend-{{ $member->uuid }}" class="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border bg-[var(--surface-raised)] p-0 text-[var(--text)] shadow-2xl backdrop:bg-[var(--overlay)]"><form method="post" action="{{ route('tenant.team.members.suspend',$member->uuid) }}" class="p-6">@csrf<h2 class="text-lg font-semibold">Suspend {{ $member->user->name }}?</h2><p class="muted mt-2">Workspace access is revoked immediately. Their account and other memberships remain available.</p><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" onclick="this.closest('dialog').close()">Cancel</button><x-button type="submit" variant="danger">Suspend member</x-button></div></form></dialog>@endcan
        @can('reactivate',$member)<dialog id="reactivate-{{ $member->uuid }}" class="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border bg-[var(--surface-raised)] p-0 text-[var(--text)] shadow-2xl backdrop:bg-[var(--overlay)]"><form method="post" action="{{ route('tenant.team.members.reactivate',$member->uuid) }}" class="p-6">@csrf<h2 class="text-lg font-semibold">Reactivate {{ $member->user->name }}?</h2><p class="muted mt-2">Their previous role and workspace access will be restored.</p><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" onclick="this.closest('dialog').close()">Cancel</button><x-button type="submit">Reactivate</x-button></div></form></dialog>@endcan
        @can('remove',$member)<dialog id="remove-{{ $member->uuid }}" class="m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl border bg-[var(--surface-raised)] p-0 text-[var(--text)] shadow-2xl backdrop:bg-[var(--overlay)]"><form method="post" action="{{ route('tenant.team.members.destroy',$member->uuid) }}" class="p-6">@csrf @method('DELETE')<h2 class="text-lg font-semibold">Remove {{ $member->user->name }}?</h2><p class="muted mt-2">They will lose access immediately. Their user account and audit history will be preserved.</p><div class="mt-6 flex justify-end gap-2"><button type="button" class="btn-secondary" onclick="this.closest('dialog').close()">Cancel</button><x-button type="submit" variant="danger">Remove member</x-button></div></form></dialog>@endcan
    @endforeach
</x-layouts.app>
