<x-layouts.app :title="isset($workflow) ? 'Edit automation' : 'New automation'">
@php
    $initialSteps = isset($workflow) ? $workflow->currentDraftVersion->steps->map(fn($s)=>['step_key'=>$s->step_key,'parent_step_key'=>$s->parent_step_key,'step_type'=>$s->step_type->value,'position'=>$s->position,'name'=>$s->name,'configuration'=>$s->configuration])->values() : collect();
    $templateData = $templates->mapWithKeys(fn($t)=>[$t->uuid=>['name'=>$t->name,'variables'=>collect($t->currentPublishedVersion?->variable_configuration ?? [])->reject(fn($v,$k)=>str_starts_with($k,'current_'))->keys()->values()] ]);
@endphp
<x-page-header :title="isset($workflow) ? 'Edit '.$workflow->name : 'Create workflow'" description="Configure a manual workflow with a simple ordered step list." />
@if($errors->any())<x-alert variant="danger" title="Workflow could not be saved"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
<form method="post" action="{{ isset($workflow) ? route('tenant.automations.update',$workflow) : route('tenant.automations.store') }}" x-data="automationBuilder(@js($initialSteps),@js($templateData))" @submit="prepare()">
    @csrf @isset($workflow) @method('PUT') <input type="hidden" name="expected_version" value="{{ $workflow->version }}"> @endisset
    <input type="hidden" name="trigger_type" value="manual"><input type="hidden" name="settings[maximum_execution_minutes]" value="60"><input type="hidden" name="settings[maximum_steps]" value="25"><input type="hidden" name="settings[allow_reentry]" value="0"><input type="hidden" name="settings[maximum_active_executions_per_contact]" value="1"><input type="hidden" name="steps_json" :value="JSON.stringify(payload)">
    <nav class="mb-5 flex gap-2 overflow-x-auto">@foreach(['Basic Information','Trigger','Steps','Review'] as $i=>$label)<button type="button" class="btn-secondary shrink-0" :class="section==={{$i+1}} && 'ring-2 ring-emerald-500'" @click="section={{$i+1}}">{{$i+1}}. {{$label}}</button>@endforeach</nav>
    <section x-show="section===1" class="card grid gap-4 md:grid-cols-2"><label>Workflow name<input class="input mt-2" name="name" maxlength="150" required value="{{ old('name',$workflow->name??'') }}"></label><label>Description<textarea class="input mt-2 min-h-28" name="description" maxlength="1000">{{ old('description',$workflow->description??'') }}</textarea></label></section>
    <section x-show="section===2" class="card"><h2 class="font-semibold">Trigger</h2><div class="mt-4 rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-4"><p class="font-medium">Manual</p><p class="text-sm text-[var(--text-muted)]">Authorized users start this workflow from its detail page. Future triggers are intentionally hidden.</p></div></section>
    <section x-show="section===3" class="space-y-4">
        <div class="card"><div class="flex flex-wrap gap-2"><template x-for="type in addTypes" :key="type.value"><button type="button" class="btn-secondary" @click="add(type.value)" x-text="'+ '+type.label"></button></template></div></div>
        <template x-for="(step,index) in steps" :key="step.step_key"><article class="card"><div class="flex flex-wrap items-center gap-2"><span class="grid size-8 place-items-center rounded-lg bg-[var(--accent-soft)] font-bold text-[var(--accent)]" x-text="index+1"></span><strong class="flex-1" x-text="label(step.step_type)"></strong><button type="button" class="btn-secondary" @click="move(index,-1)" :disabled="index===0">Up</button><button type="button" class="btn-secondary" @click="move(index,1)" :disabled="index===steps.length-1">Down</button><button type="button" class="btn-secondary text-red-500" @click="remove(index)">Remove</button></div>
            <div class="mt-4 grid gap-3 md:grid-cols-2">
                <label>Step name<input class="input mt-2" x-model="step.name" maxlength="150"></label>
                <label x-show="['condition','delay','action'].includes(step.step_type)">Next step<select class="input mt-2" x-model="step.configuration.next_step_key"><option value="">Natural completion</option><template x-for="target in steps.filter(x=>x.step_key!==step.step_key)" :key="target.step_key"><option :value="target.step_key" x-text="target.name||label(target.step_type)"></option></template></select></label>
                <template x-if="['condition','branch'].includes(step.step_type)"><div class="contents"><label>Field<select class="input mt-2" x-model="step.configuration.condition.children[0].field"><option value="trigger.type">Trigger type</option><option value="contact.company">Contact company</option><option value="contact.preferred_language">Preferred language</option><option value="contact.timezone">Timezone</option></select></label><label>Value<input class="input mt-2" x-model="step.configuration.condition.children[0].value"></label></div></template>
                <template x-if="step.step_type==='branch'"><div class="contents"><label>True path<select class="input mt-2" x-model="step.configuration.true_step_key"><option value="">Select step</option><template x-for="target in steps.filter(x=>x.step_key!==step.step_key)" :key="target.step_key"><option :value="target.step_key" x-text="target.name||label(target.step_type)"></option></template></select></label><label>False path<select class="input mt-2" x-model="step.configuration.false_step_key"><option value="">Select step</option><template x-for="target in steps.filter(x=>x.step_key!==step.step_key)" :key="target.step_key"><option :value="target.step_key" x-text="target.name||label(target.step_type)"></option></template></select></label></div></template>
                <label x-show="step.step_type==='delay'">Delay seconds<input class="input mt-2" type="number" min="60" max="604800" x-model.number="step.configuration.seconds"></label>
                <label x-show="step.step_type==='action' && step.configuration.action_type==='send_whatsapp_template'">Published template<select class="input mt-2" x-model="step.configuration.parameters.template_uuid" @change="templateChanged(step)"><option value="">Select template</option>@foreach($templates as $template)<option value="{{$template->uuid}}">{{$template->name}} · v{{$template->currentPublishedVersion?->version_number}}</option>@endforeach</select></label>
                <label x-show="step.step_type==='action' && ['add_contact_label','remove_contact_label'].includes(step.configuration.action_type)">Label<select class="input mt-2" x-model="step.configuration.parameters.label_uuid"><option value="">Select label</option>@foreach($labels as $label)<option value="{{$label->uuid}}">{{$label->name}}</option>@endforeach</select></label>
                <label x-show="step.step_type==='action' && ['add_contact_to_group','remove_contact_from_group'].includes(step.configuration.action_type)">Group<select class="input mt-2" x-model="step.configuration.parameters.group_uuid"><option value="">Select group</option>@foreach($groups as $group)<option value="{{$group->uuid}}">{{$group->name}}</option>@endforeach</select></label>
                <template x-if="step.step_type==='action' && step.configuration.action_type==='update_contact'"><div class="contents"><label>Contact field<select class="input mt-2" x-model="step.uiField"><option value="company">Company</option><option value="first_name">First name</option><option value="last_name">Last name</option><option value="preferred_language">Preferred language</option><option value="timezone">Timezone</option></select></label><label>New value<input class="input mt-2" x-model="step.uiValue"></label></div></template>
            </div>
        </article></template>
        <x-empty-state x-show="steps.length===0" title="No steps yet" description="Add at least one step to publish this workflow." />
    </section>
    <section x-show="section===4" class="card space-y-4"><h2 class="font-semibold">Review</h2><dl class="grid gap-3 sm:grid-cols-3"><div><dt class="text-[var(--text-muted)]">Trigger</dt><dd>Manual</dd></div><div><dt class="text-[var(--text-muted)]">Steps</dt><dd x-text="steps.length"></dd></div><div><dt class="text-[var(--text-muted)]">State</dt><dd>Saved as draft</dd></div></dl><p class="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 text-sm">Publishing validates resource ownership, graph paths, template versions, consent-aware actions, and safety limits.</p><button class="btn-primary">{{ isset($workflow) ? 'Save changes' : 'Create workflow' }}</button></section>
    <div class="mt-5 flex justify-between"><button x-show="section>1" type="button" class="btn-secondary" @click="section--">Previous</button><button x-show="section<4" type="button" class="btn-primary ml-auto" @click="section++">Continue</button></div>
</form>
<script>
document.addEventListener('alpine:init',()=>Alpine.data('automationBuilder',(initial,templates)=>({section:1,templates,steps:initial.map(s=>({...s,uiField:Object.keys(s.configuration?.parameters?.updates||{})[0]||'company',uiValue:Object.values(s.configuration?.parameters?.updates||{})[0]?.value||''})),payload:[],addTypes:[{value:'condition',label:'Condition'},{value:'branch',label:'Branch'},{value:'delay',label:'Delay'},{value:'send_whatsapp_template',label:'Send template'},{value:'add_contact_label',label:'Add label'},{value:'remove_contact_label',label:'Remove label'},{value:'add_contact_to_group',label:'Add group'},{value:'remove_contact_from_group',label:'Remove group'},{value:'update_contact',label:'Update contact'},{value:'stop',label:'Stop'}],label(v){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())},condition(){return{type:'group',version:1,logic:'and',children:[{type:'rule',field:'trigger.type',operator:'equals',value:'manual'}]}},add(type){let key='step_'+crypto.randomUUID().replaceAll('-','').slice(0,12),stepType=['condition','branch','delay','stop'].includes(type)?type:'action',configuration={};if(stepType==='condition')configuration={condition:this.condition(),next_step_key:''};if(stepType==='branch')configuration={condition:this.condition(),true_step_key:'',false_step_key:''};if(stepType==='delay')configuration={delay_type:'duration',seconds:60,next_step_key:''};if(stepType==='action'){configuration={action_type:type,parameters:{},next_step_key:''};if(type==='send_whatsapp_template')configuration.parameters={template_uuid:'',session_strategy:'automatic',session_uuid:null,variable_mappings:{}};if(type.includes('label'))configuration.parameters={label_uuid:''};if(type.includes('group'))configuration.parameters={group_uuid:''};if(type==='update_contact')configuration.parameters={updates:{}}}this.steps.push({step_key:key,parent_step_key:null,step_type:stepType,position:this.steps.length+1,name:this.label(type),configuration,uiField:'company',uiValue:''})},remove(i){this.steps.splice(i,1)},move(i,d){let j=i+d;if(j<0||j>=this.steps.length)return;[this.steps[i],this.steps[j]]=[this.steps[j],this.steps[i]]},templateChanged(step){let vars=this.templates[step.configuration.parameters.template_uuid]?.variables||[];step.configuration.parameters.variable_mappings={};vars.forEach(k=>step.configuration.parameters.variable_mappings[k]={source:'contact',key:k})},prepare(){this.payload=this.steps.map((s,i)=>{let c=structuredClone(s.configuration);if(s.step_type==='action'&&c.action_type==='update_contact')c.parameters.updates={[s.uiField]:{source:'constant',value:s.uiValue}};return{step_key:s.step_key,parent_step_key:i?this.steps[i-1].step_key:null,step_type:s.step_type,position:i+1,name:s.name,configuration:c}})}})))
</script>
</x-layouts.app>
