<x-layouts.app :title="$workflow->name">
<x-page-header eyebrow="Automation" :title="$workflow->name" :description="$workflow->description ?: 'Manual tenant workflow'">
    <x-slot:actions><div class="flex flex-wrap gap-2">@if($workflow->current_draft_version_id)@can('update',$workflow)<a class="btn-secondary" href="{{ route('tenant.automations.edit',$workflow) }}">Edit draft</a>@endcan @can('publish',$workflow)<form method="post" action="{{ route('tenant.automations.publish',$workflow) }}">@csrf<input type="hidden" name="expected_version" value="{{$workflow->version}}"><button class="btn-primary">Publish</button></form>@endcan @else @can('update',$workflow)<form method="post" action="{{ route('tenant.automations.draft',$workflow) }}">@csrf<input type="hidden" name="expected_version" value="{{$workflow->version}}"><button class="btn-secondary">Create draft</button></form>@endcan @endif @if($workflow->current_published_version_id)@if($workflow->is_enabled)@can('disable',$workflow)<form method="post" action="{{ route('tenant.automations.disable',$workflow) }}">@csrf<input type="hidden" name="expected_version" value="{{$workflow->version}}"><button class="btn-secondary">Disable</button></form>@endcan @else @can('enable',$workflow)<form method="post" action="{{ route('tenant.automations.enable',$workflow) }}">@csrf<input type="hidden" name="expected_version" value="{{$workflow->version}}"><button class="btn-primary">Enable</button></form>@endcan @endif @endif</div></x-slot:actions>
</x-page-header>
<div class="grid gap-5 lg:grid-cols-3"><section class="card lg:col-span-2"><h2 class="font-semibold">Overview</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-sm text-[var(--text-muted)]">Status</dt><dd><x-badge>{{str($workflow->status->value)->headline()}}</x-badge></dd></div><div><dt class="text-sm text-[var(--text-muted)]">Enabled</dt><dd>{{$workflow->is_enabled?'Yes':'No'}}</dd></div><div><dt class="text-sm text-[var(--text-muted)]">Trigger</dt><dd>Manual</dd></div><div><dt class="text-sm text-[var(--text-muted)]">Updated</dt><dd>{{$workflow->updated_at->diffForHumans()}}</dd></div></dl></section>
<aside class="card"><h2 class="font-semibold">Manual run</h2>@if($workflow->current_published_version_id && $workflow->is_enabled && ($workflow->currentPublishedVersion?->trigger_type?->value==='manual'))@can('execute',$workflow)<form class="mt-4 space-y-3" method="post" action="{{route('tenant.automations.execute',$workflow)}}">@csrf<input type="hidden" name="idempotency_key" value="{{(string)Illuminate\Support\Str::uuid()}}">@if($contacts->isNotEmpty())<label>Contact<select class="input mt-2" name="context[contact][uuid]" required><option value="">Select contact</option>@foreach($contacts as $contact)<option value="{{$contact->uuid}}">{{trim($contact->first_name.' '.$contact->last_name) ?: $contact->maskedPhone()}} · {{$contact->maskedPhone()}}</option>@endforeach</select></label>@endif<button class="btn-primary w-full">Run workflow</button></form>@endcan @else<p class="mt-3 text-sm text-[var(--text-muted)]">Publish and enable this manual workflow before running it.</p>@endif</aside></div>
<section class="mt-5 card"><h2 class="font-semibold">Versions</h2><div class="mt-4 overflow-x-auto"><table class="data-table min-w-[680px]"><thead><tr><th>Version</th><th>Status</th><th>Trigger</th><th>Steps</th><th>Published</th></tr></thead><tbody>@foreach($workflow->versions as $version)<tr><td>v{{$version->version_number}}</td><td>{{str($version->status->value)->headline()}}</td><td>{{str($version->trigger_type->value)->headline()}}</td><td>{{$version->steps_count}}</td><td>{{$version->published_at?->format('M j, Y H:i') ?? '—'}}</td></tr>@endforeach</tbody></table></div></section>
<section class="mt-5 card"><div class="flex items-center justify-between"><h2 class="font-semibold">Executions</h2><a class="btn-secondary" href="{{route('tenant.automations.executions.index',$workflow)}}">View all</a></div><div class="mt-4 overflow-x-auto"><table class="data-table min-w-[720px]"><thead><tr><th>Status</th><th>Trigger</th><th>Started</th><th>Current step</th><th>Failure</th></tr></thead><tbody>@forelse($executions as $execution)<tr><td><a class="text-emerald-500" href="{{route('tenant.automation-executions.show',$execution)}}">{{str($execution->status->value)->headline()}}</a></td><td>{{str($execution->trigger_type)->headline()}}</td><td>{{$execution->started_at?->diffForHumans() ?? 'Pending'}}</td><td>{{$execution->current_step_key ?? '—'}}</td><td>{{$execution->failure_code ?? '—'}}</td></tr>@empty<tr><td colspan="5">No executions yet.</td></tr>@endforelse</tbody></table></div></section>
</x-layouts.app>
