<?php

use App\Http\Controllers\PlatformAnalyticsController;
use App\Http\Controllers\PlatformAnalyticsDashboardController;
use App\Http\Controllers\PlatformAuditController;
use App\Http\Controllers\PlatformAutomationWorkflowController;
use App\Http\Controllers\PlatformBillingController;
use App\Http\Controllers\PlatformContactController;
use App\Http\Controllers\PlatformDashboardController;
use App\Http\Controllers\PlatformHealthController;
use App\Http\Controllers\PlatformIntegrationController;
use App\Http\Controllers\PlatformNoteController;
use App\Http\Controllers\PlatformOperationsController;
use App\Http\Controllers\PlatformPaymentGatewayController;
use App\Http\Controllers\PlatformPlanController;
use App\Http\Controllers\PlatformQueueController;
use App\Http\Controllers\PlatformSecurityController;
use App\Http\Controllers\PlatformTenantController;
use App\Http\Controllers\PlatformUserController;
use App\Http\Controllers\PlatformWhatsAppCampaignController;
use App\Http\Controllers\PlatformWhatsAppCampaignExecutionController;
use App\Http\Controllers\PlatformWhatsAppCampaignOperationsController;
use App\Http\Controllers\PlatformWhatsAppChatbotController;
use App\Http\Controllers\PlatformWhatsAppInboxController;
use App\Http\Controllers\PlatformWhatsAppMessageController;
use App\Http\Controllers\PlatformWhatsAppMessageTemplateController;
use App\Http\Controllers\PlatformWhatsAppSessionController;
use Illuminate\Support\Facades\Route;

Route::prefix('platform')->name('platform.')->middleware(['auth', 'verified', 'user.active'])->group(function (): void {
    Route::get('/', PlatformDashboardController::class)->middleware('platform.permission:platform.dashboard.view')->name('dashboard');
    Route::get('analytics', PlatformAnalyticsDashboardController::class)->middleware('platform.permission:platform.analytics.view')->name('analytics.dashboard');
    Route::get('analytics/overview', PlatformAnalyticsController::class)->middleware('platform.permission:platform.analytics.view')->name('analytics.overview');
    Route::get('chatbots', PlatformWhatsAppChatbotController::class)->middleware('platform.permission:platform.chatbots.view')->name('chatbots.index');
    Route::get('integrations', PlatformIntegrationController::class)->middleware('platform.permission:platform.integrations.view')->name('integrations.index');
    Route::get('security', PlatformSecurityController::class)->middleware('platform.permission:platform.dashboard.view')->name('security');
    Route::get('inbox/conversations', [PlatformWhatsAppInboxController::class, 'index'])->middleware('platform.permission:platform.inbox.view')->name('inbox.conversations.index');
    Route::get('inbox/conversations/{conversation:uuid}', [PlatformWhatsAppInboxController::class, 'show'])->middleware('platform.permission:platform.inbox.view')->name('inbox.conversations.show');
    Route::get('inbox/messages', [PlatformWhatsAppInboxController::class, 'messages'])->middleware('platform.permission:platform.inbox.view_messages')->name('inbox.messages.index');
    Route::get('inbox/failures', [PlatformWhatsAppInboxController::class, 'failures'])->middleware('platform.permission:platform.inbox.view_failures')->name('inbox.failures.index');
    Route::get('automations', [PlatformAutomationWorkflowController::class, 'index'])->middleware('platform.permission:platform.automations.view')->name('automations.index');
    Route::get('automations/{workflow:uuid}', [PlatformAutomationWorkflowController::class, 'show'])->middleware('platform.permission:platform.automations.view_versions')->name('automations.show');
    Route::get('automation-executions', [PlatformAutomationWorkflowController::class, 'executions'])->middleware('platform.permission:platform.automation_executions.view')->name('automation-executions.index');
    Route::get('automation-executions/{execution:uuid}', [PlatformAutomationWorkflowController::class, 'execution'])->middleware('platform.permission:platform.automation_executions.view')->name('automation-executions.show');
    Route::get('tenants', [PlatformTenantController::class, 'index'])->middleware('platform.permission:platform.tenants.view')->name('tenants.index');
    Route::get('tenants/{tenant}', [PlatformTenantController::class, 'show'])->middleware('platform.permission:platform.tenants.view')->name('tenants.show');
    Route::post('tenants/{tenant}/suspend', [PlatformTenantController::class, 'suspend'])->middleware('platform.permission:platform.tenants.manage')->name('tenants.suspend');
    Route::post('tenants/{tenant}/reactivate', [PlatformTenantController::class, 'reactivate'])->middleware('platform.permission:platform.tenants.manage')->name('tenants.reactivate');
    Route::get('users', [PlatformUserController::class, 'index'])->middleware('platform.permission:platform.users.view')->name('users.index');
    Route::get('users/{user:uuid}', [PlatformUserController::class, 'show'])->middleware('platform.permission:platform.users.view')->name('users.show');
    Route::post('users/{user:uuid}/suspend', [PlatformUserController::class, 'suspend'])->middleware('platform.permission:platform.users.manage')->name('users.suspend');
    Route::post('users/{user:uuid}/reactivate', [PlatformUserController::class, 'reactivate'])->middleware('platform.permission:platform.users.manage')->name('users.reactivate');
    Route::post('notes/{type}/{uuid}', [PlatformNoteController::class, 'store'])->middleware('platform.permission:platform.notes.manage')->name('notes.store');
    Route::get('audit', [PlatformAuditController::class, 'index'])->middleware('platform.permission:platform.audit.view')->name('audit.index');
    Route::get('queues', [PlatformQueueController::class, 'index'])->middleware('platform.permission:platform.queues.view')->name('queues.index');
    Route::get('queues/{uuid}', [PlatformQueueController::class, 'show'])->middleware('platform.permission:platform.queues.view')->name('queues.show');
    Route::post('queues/{uuid}/retry', [PlatformQueueController::class, 'retry'])->middleware('platform.permission:platform.queues.manage')->name('queues.retry');
    Route::delete('queues/{uuid}', [PlatformQueueController::class, 'destroy'])->middleware('platform.permission:platform.queues.manage')->name('queues.destroy');
    Route::get('health', PlatformHealthController::class)->middleware('platform.permission:platform.health.view')->name('health');
    Route::get('operations', PlatformOperationsController::class)->middleware('platform.permission:platform.health.view')->name('operations');
    Route::get('plans', [PlatformPlanController::class, 'index'])->middleware('platform.permission:platform.plans.view')->name('plans.index');
    Route::get('billing', [PlatformBillingController::class, 'index'])->middleware('platform.permission:platform.subscriptions.view')->name('billing.index');
    Route::get('payment-gateways', [PlatformPaymentGatewayController::class, 'index'])->middleware('platform.permission:platform.subscriptions.manage')->name('payment-gateways.index');
    Route::put('payment-gateways/{provider}', [PlatformPaymentGatewayController::class, 'update'])->middleware('platform.permission:platform.subscriptions.manage')->name('payment-gateways.update');
    Route::get('tenants/{tenant}/billing', [PlatformBillingController::class, 'show'])->middleware('platform.permission:platform.subscriptions.view')->name('tenants.billing.show');
    Route::post('tenants/{tenant}/billing/payments', [PlatformBillingController::class, 'payment'])->middleware('platform.permission:platform.subscriptions.manage')->name('tenants.billing.payments.store');
    Route::get('plans/create', [PlatformPlanController::class, 'create'])->middleware('platform.permission:platform.plans.manage')->name('plans.create');
    Route::post('plans', [PlatformPlanController::class, 'store'])->middleware('platform.permission:platform.plans.manage')->name('plans.store');
    Route::get('plans/{plan}', [PlatformPlanController::class, 'show'])->middleware('platform.permission:platform.plans.view')->name('plans.show');
    Route::get('plans/{plan}/edit', [PlatformPlanController::class, 'edit'])->middleware('platform.permission:platform.plans.manage')->name('plans.edit');
    Route::put('plans/{plan}', [PlatformPlanController::class, 'update'])->middleware('platform.permission:platform.plans.manage')->name('plans.update');
    Route::post('tenants/{tenant}/subscription/assign', [PlatformTenantController::class, 'assignPlan'])->middleware('platform.permission:platform.subscriptions.manage')->name('tenants.subscription.assign');
    Route::post('tenants/{tenant}/subscription/status', [PlatformTenantController::class, 'subscriptionStatus'])->middleware('platform.permission:platform.subscriptions.manage')->name('tenants.subscription.status');
    Route::post('tenants/{tenant}/subscription/extend', [PlatformTenantController::class, 'extendSubscription'])->middleware('platform.permission:platform.subscriptions.manage')->name('tenants.subscription.extend');
    Route::get('whatsapp-sessions', [PlatformWhatsAppSessionController::class, 'index'])->middleware('platform.permission:platform.whatsapp.view')->name('whatsapp.index');
    Route::post('whatsapp-sessions/{session}/reconnect', [PlatformWhatsAppSessionController::class, 'reconnect'])->middleware('platform.permission:platform.whatsapp.manage')->name('whatsapp.reconnect');
    Route::get('messages', [PlatformWhatsAppMessageController::class, 'index'])->middleware('platform.permission:platform.messages.view')->name('messages.index');
    Route::get('messages/{message}', [PlatformWhatsAppMessageController::class, 'show'])->middleware('platform.permission:platform.messages.view')->name('messages.show');
    Route::get('message-templates', [PlatformWhatsAppMessageTemplateController::class, 'index'])->middleware('platform.permission:platform.whatsapp_templates.view')->name('message-templates.index');
    Route::get('message-templates/{template:uuid}', [PlatformWhatsAppMessageTemplateController::class, 'show'])->middleware('platform.permission:platform.whatsapp_templates.view_versions')->name('message-templates.show');
    Route::post('messages/{message}/reconcile', [PlatformWhatsAppMessageController::class, 'reconcile'])->middleware('platform.permission:platform.messages.manage')->name('messages.reconcile');
    Route::get('contacts', [PlatformContactController::class, 'contacts'])->middleware('platform.permission:platform.contacts.view')->name('contacts.index');
    Route::get('contact-imports', [PlatformContactController::class, 'imports'])->middleware('platform.permission:platform.contact_imports.view')->name('contact-imports.index');
    Route::get('contact-segments', [PlatformContactController::class, 'segments'])->middleware('platform.permission:platform.contact_segments.view')->name('contact-segments.index');
    Route::get('campaigns', [PlatformWhatsAppCampaignController::class, 'index'])->middleware('platform.permission:platform.campaigns.view')->name('campaigns.index');
    Route::get('campaigns/{campaign:uuid}', [PlatformWhatsAppCampaignController::class, 'show'])->middleware('platform.permission:platform.campaigns.view_details')->name('campaigns.show');
    Route::get('campaign-preparations', [PlatformWhatsAppCampaignOperationsController::class, 'preparations'])->middleware('platform.permission:platform.campaigns.view_details')->name('campaign-preparations.index');
    Route::get('campaign-executions', [PlatformWhatsAppCampaignExecutionController::class, 'index'])->middleware('platform.permission:platform.campaign_executions.view')->name('campaign-executions.index');
    Route::get('campaign-executions/{execution:uuid}', [PlatformWhatsAppCampaignExecutionController::class, 'show'])->middleware('platform.permission:platform.campaign_executions.view')->name('campaign-executions.show');
    Route::post('campaign-executions/{execution:uuid}/reconcile', [PlatformWhatsAppCampaignOperationsController::class, 'reconcileExecution'])->middleware('platform.permission:platform.campaign_executions.reconcile')->name('campaign-executions.reconcile');
    Route::get('campaign-dispatch-attempts', [PlatformWhatsAppCampaignOperationsController::class, 'attempts'])->middleware('platform.permission:platform.campaign_executions.view')->name('campaign-attempts.index');
    Route::get('campaign-connector', [PlatformWhatsAppCampaignOperationsController::class, 'connector'])->middleware('platform.permission:platform.health.view')->name('campaign-connector.show');
    Route::post('campaign-connector/reconcile-transport', [PlatformWhatsAppCampaignOperationsController::class, 'reconcileTransport'])->middleware('platform.permission:platform.campaign_executions.reconcile')->name('campaign-connector.reconcile-transport');
    Route::post('campaign-connector/refresh', [PlatformWhatsAppCampaignOperationsController::class, 'refreshConnector'])->middleware('platform.permission:platform.health.view')->name('campaign-connector.refresh');
});
