<?php

declare(strict_types=1);

use App\Http\Controllers\AccountSecurityController;
use App\Http\Controllers\AnalyticsController;
use App\Http\Controllers\AnalyticsDashboardController;
use App\Http\Controllers\AutomationWorkflowActionController;
use App\Http\Controllers\AutomationWorkflowController;
use App\Http\Controllers\AutomationWorkflowExecutionController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ContactDirectoryController;
use App\Http\Controllers\ContactImportController;
use App\Http\Controllers\IntegrationController;
use App\Http\Controllers\PreviewWhatsAppMessageTemplateController;
use App\Http\Controllers\SendWhatsAppMessageFromTemplateController;
use App\Http\Controllers\SwitchTenantController;
use App\Http\Controllers\TenantAuditLogController;
use App\Http\Controllers\TenantDashboardController;
use App\Http\Controllers\TenantInvitationController;
use App\Http\Controllers\TenantMemberController;
use App\Http\Controllers\TenantRoleController;
use App\Http\Controllers\TenantSettingsController;
use App\Http\Controllers\TenantSubscriptionController;
use App\Http\Controllers\TenantTeamController;
use App\Http\Controllers\ValidateWhatsAppMessageTemplateController;
use App\Http\Controllers\WhatsAppCampaignActionController;
use App\Http\Controllers\WhatsAppCampaignAttachmentController as CampaignAttachmentController;
use App\Http\Controllers\WhatsAppCampaignController;
use App\Http\Controllers\WhatsAppCampaignExecutionActionController;
use App\Http\Controllers\WhatsAppCampaignExecutionController;
use App\Http\Controllers\WhatsAppCampaignPreparationController;
use App\Http\Controllers\WhatsAppCampaignRecipientController;
use App\Http\Controllers\WhatsAppCampaignStatusController;
use App\Http\Controllers\WhatsAppCampaignTemplateController;
use App\Http\Controllers\WhatsAppChatbotController;
use App\Http\Controllers\WhatsAppChatbotConversationStateController;
use App\Http\Controllers\WhatsAppConversationActivityController;
use App\Http\Controllers\WhatsAppConversationLabelController;
use App\Http\Controllers\WhatsAppConversationNoteController;
use App\Http\Controllers\WhatsAppConversationOperationController;
use App\Http\Controllers\WhatsAppInboxController;
use App\Http\Controllers\WhatsAppInboxConversationController;
use App\Http\Controllers\WhatsAppInboxMessageController;
use App\Http\Controllers\WhatsAppInboxReplyController;
use App\Http\Controllers\WhatsAppMessageAttachmentController;
use App\Http\Controllers\WhatsAppMessageController;
use App\Http\Controllers\WhatsAppMessageTemplateAttachmentController;
use App\Http\Controllers\WhatsAppMessageTemplateController;
use App\Http\Controllers\WhatsAppMessageTemplateTaxonomyController;
use App\Http\Controllers\WhatsAppSavedReplyController;
use App\Http\Controllers\WhatsAppSessionController;
use App\Http\Controllers\WorkspaceSelectionController;
use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function (): void {
    Route::get('/app/no-workspace', fn () => response()->view('tenant.no-workspace', status: 403))->name('tenant.no-workspace');
    Route::get('/app/access-restricted', fn () => response()->view('tenant.access-restricted', status: 423))->name('tenant.access.restricted');
});

Route::middleware(['auth', 'verified', 'user.active'])->prefix('app')->name('tenant.')->group(function (): void {
    Route::get('/workspaces', WorkspaceSelectionController::class)->name('workspaces.index');
    Route::post('/workspaces/{tenant:uuid}/switch', SwitchTenantController::class)->name('switch');

    Route::middleware('tenant.context')->group(function (): void {
        Route::get('/account/security', [AccountSecurityController::class, 'show'])->name('account.security');
        Route::put('/account/security/password', [AccountSecurityController::class, 'password'])->middleware('throttle:5,1')->name('account.security.password');
        Route::post('/account/security/sessions/revoke-others', [AccountSecurityController::class, 'revokeOthers'])->middleware('throttle:5,1')->name('account.security.sessions.revoke-others');
        Route::delete('/account/security/sessions/{session}', [AccountSecurityController::class, 'revoke'])->middleware('throttle:10,1')->name('account.security.sessions.revoke');
        Route::prefix('integrations')->name('integrations.')->middleware(['tenant.subscription', 'tenant.feature:integrations.access'])->group(function (): void {
            Route::get('/', [IntegrationController::class, 'index'])->middleware('tenant.permission:integrations.view')->name('index');
            Route::get('create', [IntegrationController::class, 'create'])->middleware('tenant.permission:integrations.create')->name('create');
            Route::post('/', [IntegrationController::class, 'store'])->middleware('tenant.permission:integrations.create')->name('store');
            Route::get('{integration}', [IntegrationController::class, 'show'])->middleware('tenant.permission:integrations.view')->name('show');
            Route::get('{integration}/edit', [IntegrationController::class, 'edit'])->middleware('tenant.permission:integrations.update')->name('edit');
            Route::put('{integration}', [IntegrationController::class, 'update'])->middleware('tenant.permission:integrations.update')->name('update');
            Route::post('{integration}/toggle', [IntegrationController::class, 'toggle'])->middleware('tenant.permission:integrations.enable')->name('toggle');
            Route::post('{integration}/archive', [IntegrationController::class, 'archive'])->middleware('tenant.permission:integrations.disable')->name('archive');
            Route::post('{integration}/rotate', [IntegrationController::class, 'rotate'])->middleware(['tenant.permission:integrations.rotate_credentials', 'throttle:credential-rotation'])->name('rotate');
            Route::post('{integration}/revoke', [IntegrationController::class, 'revoke'])->middleware(['tenant.permission:integrations.rotate_credentials', 'throttle:credential-rotation'])->name('revoke');
        });
        Route::prefix('chatbots')->name('chatbots.')->middleware(['tenant.subscription', 'tenant.feature:chatbots.access'])->group(function (): void {
            Route::get('/', [WhatsAppChatbotController::class, 'index'])->middleware('tenant.permission:chatbots.view')->name('index');
            Route::get('create', [WhatsAppChatbotController::class, 'create'])->middleware('tenant.permission:chatbots.create')->name('create');
            Route::post('/', [WhatsAppChatbotController::class, 'store'])->middleware('tenant.permission:chatbots.create')->name('store');
            Route::get('{chatbot}', [WhatsAppChatbotController::class, 'show'])->middleware('tenant.permission:chatbots.view')->name('show');
            Route::get('{chatbot}/edit', [WhatsAppChatbotController::class, 'edit'])->middleware('tenant.permission:chatbots.update')->name('edit');
            Route::put('{chatbot}', [WhatsAppChatbotController::class, 'update'])->middleware('tenant.permission:chatbots.update')->name('update');
            Route::post('{chatbot}/publish', [WhatsAppChatbotController::class, 'publish'])->middleware('tenant.permission:chatbots.publish')->name('publish');
            Route::post('{chatbot}/toggle', [WhatsAppChatbotController::class, 'toggle'])->middleware('tenant.permission:chatbots.enable')->name('toggle');
            Route::post('{chatbot}/archive', [WhatsAppChatbotController::class, 'archive'])->middleware('tenant.permission:chatbots.archive')->name('archive');
            Route::post('{chatbot}/restore', [WhatsAppChatbotController::class, 'restore'])->middleware('tenant.permission:chatbots.archive')->name('restore');
        });
        Route::post('/inbox/conversations/{conversation}/chatbot/{state}', WhatsAppChatbotConversationStateController::class)->whereIn('state', ['active', 'stopped'])->middleware(['tenant.permission:chatbots.control_conversation', 'tenant.subscription', 'tenant.feature:chatbots.access', 'throttle:chatbot-state'])->name('inbox.conversations.chatbot-state');
        Route::prefix('analytics')->name('analytics.')->middleware(['tenant.permission:analytics.view', 'tenant.subscription', 'tenant.feature:analytics.access'])->group(function (): void {
            Route::get('/', AnalyticsDashboardController::class)->name('dashboard');
            Route::get('overview', [AnalyticsController::class, 'overview'])->name('overview');
            Route::get('messages', [AnalyticsController::class, 'messages'])->name('messages');
            Route::get('campaigns', [AnalyticsController::class, 'campaigns'])->name('campaigns');
            Route::get('automations', [AnalyticsController::class, 'automations'])->name('automations');
            Route::get('inbox', [AnalyticsController::class, 'inbox'])->name('inbox');
            Route::get('sessions', [AnalyticsController::class, 'sessions'])->name('sessions');
            Route::get('usage', [AnalyticsController::class, 'usage'])->middleware('tenant.permission:analytics.view_usage')->name('usage');
        });
        Route::get('/inbox', WhatsAppInboxController::class)->middleware('tenant.permission:inbox.view')->name('inbox.overview');
        Route::get('/inbox/conversations', [WhatsAppInboxConversationController::class, 'index'])->middleware('tenant.permission:inbox.view_conversations')->name('inbox.conversations.index');
        Route::get('/inbox/conversations/{conversation}', [WhatsAppInboxConversationController::class, 'show'])->middleware('tenant.permission:inbox.view_conversations')->name('inbox.conversations.show');
        Route::get('/inbox/conversations/{conversation}/messages', [WhatsAppInboxMessageController::class, 'index'])->middleware('tenant.permission:inbox.view_messages')->name('inbox.conversations.messages.index');
        Route::post('/inbox/conversations/{conversation:uuid}/reply', WhatsAppInboxReplyController::class)->middleware(['tenant.permission:inbox.reply', 'tenant.subscription', 'tenant.feature:messages.send', 'throttle:inbox-replies'])->name('inbox.conversations.reply');
        Route::post('/inbox/conversations/{conversation:uuid}/assign', [WhatsAppConversationOperationController::class, 'assign'])->middleware('tenant.permission:inbox.assign')->name('inbox.conversations.assign');
        Route::post('/inbox/conversations/{conversation:uuid}/status', [WhatsAppConversationOperationController::class, 'status'])->middleware('tenant.permission:inbox.change_status')->name('inbox.conversations.status');
        Route::post('/inbox/conversations/{conversation:uuid}/priority', [WhatsAppConversationOperationController::class, 'priority'])->middleware('tenant.permission:inbox.change_priority')->name('inbox.conversations.priority');
        Route::post('/inbox/conversations/{conversation:uuid}/read', [WhatsAppConversationOperationController::class, 'read'])->middleware('tenant.permission:inbox.mark_read')->name('inbox.conversations.read');
        Route::post('/inbox/conversations/{conversation:uuid}/unread', [WhatsAppConversationOperationController::class, 'unread'])->middleware('tenant.permission:inbox.mark_read')->name('inbox.conversations.unread');
        Route::get('/inbox/conversations/{conversation:uuid}/notes', [WhatsAppConversationNoteController::class, 'index'])->middleware('tenant.permission:inbox.view_conversations')->name('inbox.notes.index');
        Route::post('/inbox/conversations/{conversation:uuid}/notes', [WhatsAppConversationNoteController::class, 'store'])->middleware('tenant.permission:inbox.add_notes')->name('inbox.notes.store');
        Route::put('/inbox/notes/{note:uuid}', [WhatsAppConversationNoteController::class, 'update'])->middleware('tenant.permission:inbox.edit_own_notes')->name('inbox.notes.update');
        Route::delete('/inbox/notes/{note:uuid}', [WhatsAppConversationNoteController::class, 'destroy'])->middleware('tenant.permission:inbox.delete_own_notes')->name('inbox.notes.destroy');
        Route::post('/inbox/conversations/{conversation:uuid}/labels', WhatsAppConversationLabelController::class)->middleware('tenant.permission:inbox.manage_labels')->name('inbox.conversations.labels');
        Route::get('/inbox/conversations/{conversation:uuid}/activity', WhatsAppConversationActivityController::class)->middleware('tenant.permission:inbox.view_activity')->name('inbox.conversations.activity');
        Route::get('/inbox/saved-replies', [WhatsAppSavedReplyController::class, 'index'])->middleware('tenant.permission:inbox.manage_saved_replies')->name('inbox.saved-replies.index');
        Route::post('/inbox/saved-replies', [WhatsAppSavedReplyController::class, 'store'])->middleware('tenant.permission:inbox.manage_saved_replies')->name('inbox.saved-replies.store');
        Route::put('/inbox/saved-replies/{savedReply:uuid}', [WhatsAppSavedReplyController::class, 'update'])->middleware('tenant.permission:inbox.manage_saved_replies')->name('inbox.saved-replies.update');
        Route::post('/inbox/saved-replies/{savedReply:uuid}/archive', [WhatsAppSavedReplyController::class, 'archive'])->middleware('tenant.permission:inbox.manage_saved_replies')->name('inbox.saved-replies.archive');
        Route::post('/inbox/saved-replies/{savedReply}/restore', [WhatsAppSavedReplyController::class, 'restore'])->middleware('tenant.permission:inbox.manage_saved_replies')->name('inbox.saved-replies.restore');
        Route::get('/automations', [AutomationWorkflowController::class, 'index'])->middleware('tenant.permission:automations.view')->name('automations.index');
        Route::get('/automations/create', [AutomationWorkflowController::class, 'create'])->middleware('tenant.permission:automations.create')->name('automations.create');
        Route::post('/automations', [AutomationWorkflowController::class, 'store'])->middleware(['tenant.permission:automations.create', 'tenant.subscription', 'tenant.feature:automations.access', 'tenant.capacity:automations.max'])->name('automations.store');
        Route::get('/automations/{workflow:uuid}', [AutomationWorkflowController::class, 'show'])->middleware('tenant.permission:automations.view')->name('automations.show');
        Route::get('/automations/{workflow:uuid}/edit', [AutomationWorkflowController::class, 'edit'])->middleware('tenant.permission:automations.update')->name('automations.edit');
        Route::put('/automations/{workflow:uuid}', [AutomationWorkflowController::class, 'update'])->middleware(['tenant.permission:automations.update', 'tenant.subscription', 'tenant.feature:automations.access'])->name('automations.update');
        Route::post('/automations/{workflow:uuid}/draft', [AutomationWorkflowActionController::class, 'draft'])->middleware(['tenant.permission:automations.update', 'tenant.subscription', 'tenant.feature:automations.access'])->name('automations.draft');
        Route::post('/automations/{workflow:uuid}/publish', [AutomationWorkflowActionController::class, 'publish'])->middleware(['tenant.permission:automations.publish', 'tenant.subscription', 'tenant.feature:automations.access'])->name('automations.publish');
        Route::post('/automations/{workflow:uuid}/validate', [AutomationWorkflowActionController::class, 'validateWorkflow'])->middleware(['tenant.permission:automations.update', 'tenant.subscription', 'tenant.feature:automations.access'])->name('automations.validate');
        Route::post('/automations/{workflow:uuid}/enable', [AutomationWorkflowActionController::class, 'enable'])->middleware(['tenant.permission:automations.enable', 'tenant.subscription', 'tenant.feature:automations.access'])->name('automations.enable');
        Route::post('/automations/{workflow:uuid}/disable', [AutomationWorkflowActionController::class, 'disable'])->middleware('tenant.permission:automations.disable')->name('automations.disable');
        Route::post('/automations/{workflow:uuid}/duplicate', [AutomationWorkflowActionController::class, 'duplicate'])->middleware(['tenant.permission:automations.duplicate', 'tenant.subscription', 'tenant.feature:automations.access', 'tenant.capacity:automations.max'])->name('automations.duplicate');
        Route::post('/automations/{workflow:uuid}/archive', [AutomationWorkflowActionController::class, 'archive'])->middleware('tenant.permission:automations.archive')->name('automations.archive');
        Route::post('/automations/{workflow:uuid}/restore', [AutomationWorkflowActionController::class, 'restore'])->middleware('tenant.permission:automations.restore')->name('automations.restore');
        Route::post('/automations/{workflow:uuid}/execute', [AutomationWorkflowExecutionController::class, 'start'])->middleware(['tenant.permission:automations.execute', 'tenant.subscription', 'tenant.feature:automations.access', 'throttle:automation-manual'])->name('automations.execute');
        Route::get('/automations/{workflow:uuid}/executions', [AutomationWorkflowExecutionController::class, 'index'])->middleware('tenant.permission:automations.view_executions')->name('automations.executions.index');
        Route::get('/automations/executions/{execution:uuid}', [AutomationWorkflowExecutionController::class, 'show'])->middleware('tenant.permission:automations.view_executions')->name('automation-executions.show');
        Route::post('/automations/executions/{execution:uuid}/cancel', [AutomationWorkflowExecutionController::class, 'cancel'])->middleware('tenant.permission:automations.cancel_execution')->name('automation-executions.cancel');
        Route::get('/subscription', TenantSubscriptionController::class)->middleware('tenant.permission:billing.view')->name('subscription.show');
        Route::get('/billing', TenantSubscriptionController::class)->middleware('tenant.permission:billing.view')->name('billing.show');
        Route::middleware(['tenant.subscription', 'tenant.feature:whatsapp.sessions'])->group(function (): void {
            Route::get('/whatsapp-sessions', [WhatsAppSessionController::class, 'index'])->middleware('tenant.permission:sessions.view')->name('whatsapp.index');
            Route::post('/whatsapp-sessions', [WhatsAppSessionController::class, 'store'])->middleware(['tenant.permission:sessions.manage', 'tenant.capacity:whatsapp_sessions.max'])->name('whatsapp.store');
            Route::get('/whatsapp-sessions/{sessionUuid}', [WhatsAppSessionController::class, 'show'])->middleware('tenant.permission:sessions.view')->name('whatsapp.show');
            Route::get('/whatsapp-sessions/{sessionUuid}/status', [WhatsAppSessionController::class, 'status'])->middleware(['tenant.permission:sessions.view', 'throttle:60,1'])->name('whatsapp.status');
            Route::get('/whatsapp-sessions/{sessionUuid}/qr', [WhatsAppSessionController::class, 'qr'])->middleware(['tenant.permission:sessions.manage', 'throttle:30,1'])->name('whatsapp.qr');
            Route::post('/whatsapp-sessions/{sessionUuid}/reconnect', [WhatsAppSessionController::class, 'reconnect'])->middleware('tenant.permission:sessions.manage')->name('whatsapp.reconnect');
            Route::post('/whatsapp-sessions/{sessionUuid}/disconnect', [WhatsAppSessionController::class, 'disconnect'])->middleware('tenant.permission:sessions.manage')->name('whatsapp.disconnect');
            Route::delete('/whatsapp-sessions/{sessionUuid}', [WhatsAppSessionController::class, 'destroy'])->middleware('tenant.permission:sessions.manage')->name('whatsapp.destroy');
        });
        Route::view('/onboarding', 'tenant.onboarding')->name('onboarding');
        Route::get('/contacts', [ContactController::class, 'index'])->middleware('tenant.permission:contacts.view')->name('contacts.index');
        Route::get('/contacts/create', [ContactController::class, 'create'])->middleware(['tenant.permission:contacts.manage', 'tenant.subscription', 'tenant.feature:contacts.manage'])->name('contacts.create');
        Route::post('/contacts', [ContactController::class, 'store'])->middleware(['tenant.permission:contacts.manage', 'tenant.subscription', 'tenant.feature:contacts.manage', 'tenant.capacity:contacts.max'])->name('contacts.store');
        Route::get('/contacts/{contactUuid}', [ContactController::class, 'show'])->middleware('tenant.permission:contacts.view')->name('contacts.show');
        Route::get('/contacts/{contactUuid}/edit', [ContactController::class, 'edit'])->middleware('tenant.permission:contacts.manage')->name('contacts.edit');
        Route::put('/contacts/{contactUuid}', [ContactController::class, 'update'])->middleware('tenant.permission:contacts.manage')->name('contacts.update');
        Route::post('/contacts/{contactUuid}/consent', [ContactController::class, 'consent'])->middleware('tenant.permission:contacts.manage')->name('contacts.consent');
        Route::post('/contacts/{contactUuid}/safety/{action}', [ContactController::class, 'exclusion'])->middleware('tenant.permission:contacts.manage')->name('contacts.safety');
        Route::post('/contacts/{contactUuid}/archive', [ContactController::class, 'archive'])->middleware('tenant.permission:contacts.manage')->name('contacts.archive');
        Route::post('/contacts/{contactUuid}/restore', [ContactController::class, 'restore'])->middleware('tenant.permission:contacts.manage')->name('contacts.restore');
        Route::get('/contact-groups', [ContactDirectoryController::class, 'groups'])->middleware('tenant.permission:contacts.view')->name('contact-groups.index');
        Route::get('/contact-labels', [ContactDirectoryController::class, 'labels'])->middleware('tenant.permission:contacts.view')->name('contact-labels.index');
        Route::post('/contact-{kind}', [ContactDirectoryController::class, 'store'])->middleware('tenant.permission:contacts.manage')->name('contact-taxonomy.store');
        Route::post('/contact-{kind}/{uuid}/assign', [ContactDirectoryController::class, 'assign'])->middleware('tenant.permission:contacts.manage')->name('contact-taxonomy.assign');
        Route::get('/contact-imports', [ContactImportController::class, 'index'])->middleware('tenant.permission:contacts.view')->name('contact-imports.index');
        Route::post('/contact-imports', [ContactImportController::class, 'store'])->middleware(['tenant.permission:contacts.manage', 'tenant.subscription', 'tenant.feature:contacts.manage'])->name('contact-imports.store');
        Route::post('/contact-imports/{importUuid}/rollback', [ContactImportController::class, 'rollback'])->middleware('tenant.permission:contacts.manage')->name('contact-imports.rollback');
        Route::get('/contact-segments', [ContactDirectoryController::class, 'segments'])->middleware('tenant.permission:contacts.view')->name('contact-segments.index');
        Route::post('/contact-segments', [ContactDirectoryController::class, 'segmentStore'])->middleware('tenant.permission:contacts.manage')->name('contact-segments.store');
        Route::get('/messages', [WhatsAppMessageController::class, 'index'])->middleware('tenant.permission:messages.view')->name('messages.index');
        Route::get('/messages/compose', [WhatsAppMessageController::class, 'create'])->middleware(['tenant.permission:messages.send', 'tenant.subscription', 'tenant.feature:messages.send'])->name('messages.create');
        Route::post('/messages', [WhatsAppMessageController::class, 'store'])->middleware(['tenant.permission:messages.send', 'tenant.subscription', 'tenant.feature:messages.send', 'tenant.capacity:messages.monthly', 'throttle:30,1'])->name('messages.store');
        Route::post('/messages/from-template', SendWhatsAppMessageFromTemplateController::class)->middleware(['tenant.permission:messages.send', 'tenant.permission:whatsapp_templates.use', 'tenant.subscription', 'tenant.feature:messages.send', 'tenant.feature:whatsapp_message_templates', 'tenant.capacity:messages.monthly', 'throttle:30,1'])->name('messages.from-template');
        Route::get('/messages/{messageUuid}', [WhatsAppMessageController::class, 'show'])->middleware('tenant.permission:messages.view')->name('messages.show');
        Route::get('/messages/{messageUuid}/status', [WhatsAppMessageController::class, 'status'])->middleware(['tenant.permission:messages.view', 'throttle:60,1'])->name('messages.status');
        Route::get('/messages/{messageUuid}/attachment', WhatsAppMessageAttachmentController::class)->middleware(['tenant.permission:messages.view', 'throttle:30,1'])->name('messages.attachment');
        Route::post('/messages/{messageUuid}/cancel', [WhatsAppMessageController::class, 'cancel'])->middleware('tenant.permission:messages.send')->name('messages.cancel');
        Route::post('/messages/{messageUuid}/retry', [WhatsAppMessageController::class, 'retry'])->middleware(['tenant.permission:messages.send', 'tenant.subscription', 'tenant.feature:messages.send'])->name('messages.retry');
        Route::get('/message-templates', [WhatsAppMessageTemplateController::class, 'index'])->middleware('tenant.permission:whatsapp_templates.view')->name('message-templates.index');
        Route::get('/message-templates/create', [WhatsAppMessageTemplateController::class, 'create'])->middleware('tenant.permission:whatsapp_templates.create')->name('message-templates.create');
        Route::post('/message-templates', [WhatsAppMessageTemplateController::class, 'store'])->middleware(['tenant.permission:whatsapp_templates.create', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates', 'tenant.capacity:whatsapp_message_templates.max'])->name('message-templates.store');
        Route::get('/message-templates/{template:uuid}', [WhatsAppMessageTemplateController::class, 'show'])->middleware('tenant.permission:whatsapp_templates.view')->name('message-templates.show');
        Route::get('/message-templates/{template:uuid}/edit', [WhatsAppMessageTemplateController::class, 'edit'])->middleware('tenant.permission:whatsapp_templates.update')->name('message-templates.edit');
        Route::put('/message-templates/{template:uuid}', [WhatsAppMessageTemplateController::class, 'update'])->middleware(['tenant.permission:whatsapp_templates.update', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.update');
        Route::post('/message-templates/{template:uuid}/draft', [WhatsAppMessageTemplateController::class, 'draft'])->middleware(['tenant.permission:whatsapp_templates.update', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.draft');
        Route::post('/message-templates/{template:uuid}/publish', [WhatsAppMessageTemplateController::class, 'publish'])->middleware(['tenant.permission:whatsapp_templates.publish', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.publish');
        Route::post('/message-templates/{template:uuid}/duplicate', [WhatsAppMessageTemplateController::class, 'duplicate'])->middleware(['tenant.permission:whatsapp_templates.duplicate', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates', 'tenant.capacity:whatsapp_message_templates.max'])->name('message-templates.duplicate');
        Route::post('/message-templates/{template:uuid}/archive', [WhatsAppMessageTemplateController::class, 'archive'])->middleware(['tenant.permission:whatsapp_templates.archive', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.archive');
        Route::post('/message-templates/{template:uuid}/restore', [WhatsAppMessageTemplateController::class, 'restore'])->middleware(['tenant.permission:whatsapp_templates.restore', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.restore');
        Route::post('/message-templates/{template:uuid}/validate', ValidateWhatsAppMessageTemplateController::class)->middleware(['tenant.permission:whatsapp_templates.update', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.validate');
        Route::post('/message-templates/{template:uuid}/preview', PreviewWhatsAppMessageTemplateController::class)->middleware(['tenant.permission:whatsapp_templates.view', 'throttle:template-preview'])->name('message-templates.preview');
        Route::post('/message-templates/{template:uuid}/attachment', [WhatsAppMessageTemplateAttachmentController::class, 'store'])->middleware(['tenant.permission:whatsapp_templates.manage_media', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.attachment.store');
        Route::delete('/message-templates/{template:uuid}/attachment', [WhatsAppMessageTemplateAttachmentController::class, 'destroy'])->middleware(['tenant.permission:whatsapp_templates.manage_media', 'tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.attachment.destroy');
        Route::get('/message-template-categories', [WhatsAppMessageTemplateTaxonomyController::class, 'categories'])->middleware('tenant.permission:whatsapp_templates.view')->name('message-template-categories.index');
        Route::post('/message-template-categories', [WhatsAppMessageTemplateTaxonomyController::class, 'storeCategory'])->middleware('tenant.permission:whatsapp_templates.manage_categories')->name('message-template-categories.store');
        Route::put('/message-template-categories/{category:uuid}', [WhatsAppMessageTemplateTaxonomyController::class, 'updateCategory'])->middleware('tenant.permission:whatsapp_templates.manage_categories')->name('message-template-categories.update');
        Route::post('/message-template-categories/{category:uuid}/archive', [WhatsAppMessageTemplateTaxonomyController::class, 'archiveCategory'])->middleware('tenant.permission:whatsapp_templates.manage_categories')->name('message-template-categories.archive');
        Route::post('/message-template-categories/{categoryUuid}/restore', [WhatsAppMessageTemplateTaxonomyController::class, 'restoreCategory'])->middleware('tenant.permission:whatsapp_templates.manage_categories')->name('message-template-categories.restore');
        Route::get('/message-template-labels', [WhatsAppMessageTemplateTaxonomyController::class, 'labels'])->middleware('tenant.permission:whatsapp_templates.view')->name('message-template-labels.index');
        Route::post('/message-template-labels', [WhatsAppMessageTemplateTaxonomyController::class, 'storeLabel'])->middleware('tenant.permission:whatsapp_templates.manage_labels')->name('message-template-labels.store');
        Route::put('/message-template-labels/{label:uuid}', [WhatsAppMessageTemplateTaxonomyController::class, 'updateLabel'])->middleware('tenant.permission:whatsapp_templates.manage_labels')->name('message-template-labels.update');
        Route::post('/message-template-labels/{label:uuid}/archive', [WhatsAppMessageTemplateTaxonomyController::class, 'archiveLabel'])->middleware('tenant.permission:whatsapp_templates.manage_labels')->name('message-template-labels.archive');
        Route::post('/message-template-labels/{labelUuid}/restore', [WhatsAppMessageTemplateTaxonomyController::class, 'restoreLabel'])->middleware('tenant.permission:whatsapp_templates.manage_labels')->name('message-template-labels.restore');
        Route::post('/message-templates/{template:uuid}/labels', [WhatsAppMessageTemplateTaxonomyController::class, 'assign'])->middleware(['tenant.subscription', 'tenant.feature:whatsapp_message_templates'])->name('message-templates.labels');
        Route::get('/campaigns', [WhatsAppCampaignController::class, 'index'])->middleware('tenant.permission:campaigns.view')->name('campaigns.index');
        Route::get('/campaigns/create', [WhatsAppCampaignController::class, 'create'])->middleware(['tenant.permission:campaigns.create', 'tenant.subscription', 'tenant.feature:campaigns.manage'])->name('campaigns.create');
        Route::post('/campaigns', [WhatsAppCampaignController::class, 'store'])->middleware(['tenant.permission:campaigns.create', 'tenant.subscription', 'tenant.feature:campaigns.manage'])->name('campaigns.store');
        Route::get('/campaigns/{campaign:uuid}', [WhatsAppCampaignController::class, 'show'])->middleware('tenant.permission:campaigns.view')->name('campaigns.show');
        Route::get('/campaigns/{campaign:uuid}/status', WhatsAppCampaignStatusController::class)->middleware(['tenant.permission:campaigns.view', 'throttle:60,1'])->name('campaigns.status');
        Route::get('/campaigns/{campaign:uuid}/edit', [WhatsAppCampaignController::class, 'edit'])->middleware('tenant.permission:campaigns.update')->name('campaigns.edit');
        Route::put('/campaigns/{campaign:uuid}', [WhatsAppCampaignController::class, 'update'])->middleware('tenant.permission:campaigns.update')->name('campaigns.update');
        Route::post('/campaigns/{campaign:uuid}/template', [WhatsAppCampaignTemplateController::class, 'apply'])->middleware(['tenant.permission:campaigns.update', 'tenant.permission:whatsapp_templates.use', 'tenant.subscription', 'tenant.feature:campaigns.manage', 'tenant.feature:whatsapp_message_templates'])->name('campaigns.template.apply');
        Route::delete('/campaigns/{campaign:uuid}/template', [WhatsAppCampaignTemplateController::class, 'detach'])->middleware(['tenant.permission:campaigns.update', 'tenant.permission:whatsapp_templates.use'])->name('campaigns.template.detach');
        Route::post('/campaigns/{campaign:uuid}/duplicate', [WhatsAppCampaignActionController::class, 'duplicate'])->middleware('tenant.permission:campaigns.duplicate')->name('campaigns.duplicate');
        Route::post('/campaigns/{campaign:uuid}/validate', [WhatsAppCampaignActionController::class, 'validateCampaign'])->middleware('tenant.permission:campaigns.update')->name('campaigns.validate');
        Route::post('/campaigns/{campaign:uuid}/schedule', [WhatsAppCampaignActionController::class, 'schedule'])->middleware(['tenant.permission:campaigns.schedule', 'tenant.feature:campaigns.schedule'])->name('campaigns.schedule');
        Route::post('/campaigns/{campaign:uuid}/unschedule', [WhatsAppCampaignActionController::class, 'unschedule'])->middleware('tenant.permission:campaigns.schedule')->name('campaigns.unschedule');
        Route::post('/campaigns/{campaign:uuid}/archive', [WhatsAppCampaignActionController::class, 'archive'])->middleware('tenant.permission:campaigns.archive')->name('campaigns.archive');
        Route::get('/campaigns/{campaign:uuid}/events', [WhatsAppCampaignController::class, 'show'])->middleware('tenant.permission:campaigns.view_events')->name('campaigns.events');
        Route::get('/campaigns/{campaign:uuid}/timeline', [WhatsAppCampaignController::class, 'show'])->middleware('tenant.permission:campaigns.view_events')->name('campaigns.timeline');
        Route::get('/campaigns/{campaign:uuid}/attachment', CampaignAttachmentController::class)->middleware('tenant.permission:campaigns.view_content')->name('campaigns.attachment');
        Route::post('/campaigns/{campaign:uuid}/audience-estimate', [WhatsAppCampaignPreparationController::class, 'estimate'])->middleware(['tenant.permission:campaigns.view', 'throttle:20,1'])->name('campaigns.audience-estimate');
        Route::post('/campaigns/{campaign:uuid}/prepare', [WhatsAppCampaignPreparationController::class, 'prepare'])->middleware(['tenant.permission:campaigns.prepare', 'tenant.subscription', 'tenant.feature:campaigns.manage', 'throttle:10,1'])->name('campaigns.prepare');
        Route::post('/campaigns/{campaign:uuid}/preparation/cancel', [WhatsAppCampaignPreparationController::class, 'cancel'])->middleware('tenant.permission:campaigns.prepare')->name('campaigns.preparation.cancel');
        Route::post('/campaigns/{campaign:uuid}/preparation/invalidate', [WhatsAppCampaignPreparationController::class, 'invalidate'])->middleware('tenant.permission:campaigns.prepare')->name('campaigns.preparation.invalidate');
        Route::get('/campaigns/{campaign:uuid}/recipients', [WhatsAppCampaignRecipientController::class, 'recipients'])->middleware('tenant.permission:campaigns.view_recipients')->name('campaigns.recipients');
        Route::get('/campaigns/{campaign:uuid}/exclusions', [WhatsAppCampaignRecipientController::class, 'exclusions'])->middleware('tenant.permission:campaigns.view_recipients')->name('campaigns.exclusions');
        Route::post('/campaigns/{campaign:uuid}/launch', [WhatsAppCampaignExecutionActionController::class, 'launch'])->middleware(['tenant.permission:campaigns.launch', 'tenant.subscription', 'tenant.feature:campaigns.manage', 'throttle:10,1'])->name('campaigns.launch');
        Route::post('/campaigns/{campaign:uuid}/pause', [WhatsAppCampaignExecutionActionController::class, 'pause'])->middleware('tenant.permission:campaigns.pause')->name('campaigns.pause');
        Route::post('/campaigns/{campaign:uuid}/resume', [WhatsAppCampaignExecutionActionController::class, 'resume'])->middleware(['tenant.permission:campaigns.resume', 'tenant.subscription'])->name('campaigns.resume');
        Route::post('/campaigns/{campaign:uuid}/cancel', [WhatsAppCampaignExecutionActionController::class, 'cancel'])->middleware('tenant.permission:campaigns.cancel')->name('campaigns.execution.cancel');
        Route::get('/campaigns/{campaign:uuid}/execution', [WhatsAppCampaignExecutionController::class, 'show'])->middleware('tenant.permission:campaigns.view_execution')->name('campaigns.execution');
        Route::get('/campaigns/{campaign:uuid}/execution/recipients', [WhatsAppCampaignExecutionController::class, 'recipients'])->middleware('tenant.permission:campaigns.view_execution')->name('campaigns.execution.recipients');
        Route::get('/campaigns/{campaign:uuid}/execution/attempts', [WhatsAppCampaignExecutionController::class, 'attempts'])->middleware('tenant.permission:campaigns.view_execution')->name('campaigns.execution.attempts');
        Route::post('/campaigns/{campaign:uuid}/execution/recipients/{recipientExecution:uuid}/retry', [WhatsAppCampaignExecutionController::class, 'retry'])->middleware('tenant.permission:campaigns.retry_failed')->name('campaigns.execution.recipients.retry');
        Route::get('/dashboard', TenantDashboardController::class)->name('dashboard');
        Route::get('/settings', [TenantSettingsController::class, 'edit'])->middleware('tenant.permission:settings.manage')->name('settings.edit');
        Route::put('/settings', [TenantSettingsController::class, 'update'])->middleware('tenant.permission:settings.manage')->name('settings.update');
        Route::get('/audit-logs', [TenantAuditLogController::class, 'index'])->middleware('tenant.permission:audit_logs.view')->name('audit.index');
        Route::get('/audit-logs/{auditUuid}', [TenantAuditLogController::class, 'show'])->middleware('tenant.permission:audit_logs.view')->name('audit.show');
        Route::get('/team', TenantTeamController::class)->middleware('tenant.permission:team.view')->name('team.index');
        Route::get('/team/invitations', [TenantInvitationController::class, 'index'])->middleware('tenant.permission:team.view')->name('team.invitations.index');
        Route::post('/team/invitations', [TenantInvitationController::class, 'store'])->middleware('tenant.permission:team.invite')->name('team.invitations.store');
        Route::post('/team/invitations/{invitationUuid}/resend', [TenantInvitationController::class, 'resend'])->middleware('tenant.permission:team.invite')->name('team.invitations.resend');
        Route::delete('/team/invitations/{invitationUuid}', [TenantInvitationController::class, 'revoke'])->middleware('tenant.permission:team.invite')->name('team.invitations.revoke');
        Route::put('/team/members/{membershipUuid}/role', [TenantMemberController::class, 'role'])->middleware('tenant.permission:team.update')->name('team.members.role.update');
        Route::post('/team/members/{membershipUuid}/suspend', [TenantMemberController::class, 'suspend'])->middleware('tenant.permission:team.update')->name('team.members.suspend');
        Route::post('/team/members/{membershipUuid}/reactivate', [TenantMemberController::class, 'reactivate'])->middleware('tenant.permission:team.update')->name('team.members.reactivate');
        Route::delete('/team/members/{membershipUuid}', [TenantMemberController::class, 'destroy'])->middleware('tenant.permission:team.remove')->name('team.members.destroy');
        Route::resource('roles', TenantRoleController::class)
            ->parameters(['roles' => 'roleUuid'])
            ->middleware('tenant.permission:roles.view');
    });
});

Route::redirect('/dashboard', '/app/dashboard')->middleware('auth')->name('dashboard');
