<x-layouts.app title="Compose message">
 <x-page-header eyebrow="Transactional messaging" title="Compose one message" description="Send to one consented recipient using a connected WhatsApp session."><x-slot:actions><a class="btn-secondary" href="{{ route('tenant.messages.index') }}">Back to history</a></x-slot:actions></x-page-header>
 <div class="mt-7 grid gap-6 lg:grid-cols-[minmax(0,720px)_1fr]"><form method="post" :action="template?'{{ route('tenant.messages.from-template') }}':'{{ route('tenant.messages.store') }}'" enctype="multipart/form-data" class="panel" x-data="{type:'{{ old('message_type','text') }}',template:''}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Illuminate\Support\Str::uuid() }}">
  @if($sessions->isEmpty())<x-alert variant="warning">No ready session is available. Connect a WhatsApp session before composing.</x-alert>@endif
  <label class="field-label" for="session_uuid">Connected session</label><select class="field mt-2" id="session_uuid" name="session_uuid" required><option value="">Select a session</option>@foreach($sessions as $session)<option value="{{ $session->uuid }}">{{ $session->name }}</option>@endforeach</select>
  <label class="field-label mt-5" for="recipient">Recipient</label><input class="field mt-2" id="recipient" name="recipient" value="{{ old('recipient') }}" placeholder="+15551234567" required inputmode="tel"><p class="mt-1 text-xs text-[var(--text-muted)]">International format with country code. Groups and broadcast identifiers are rejected.</p>
  <label class="field-label mt-5" for="template_uuid">Published template (optional)</label><select class="field mt-2" id="template_uuid" name="template_uuid" x-model="template"><option value="">Write message manually</option>@foreach($messageTemplates as $messageTemplate)<option value="{{ $messageTemplate->uuid }}">{{ $messageTemplate->name }} · {{ ucfirst($messageTemplate->type->value) }} · v{{ $messageTemplate->currentPublishedVersion->version_number }}</option>@endforeach</select><p x-show="template" class="mt-1 text-xs text-[var(--text-muted)]">The saved published version is rendered and queued through the existing send flow. Required variable values may be entered below.</p>
  <div x-show="template" class="mt-4 grid gap-3 sm:grid-cols-2"><label class="field-label">First name<input class="field mt-2" name="values[first_name]"></label><label class="field-label">Company<input class="field mt-2" name="values[company]"></label><input type="hidden" name="timezone" value="{{ $activeTenant->timezone??'UTC' }}"></div>
  <div x-show="!template"><label class="field-label mt-5" for="message_type">Message type</label><select class="field mt-2" id="message_type" name="message_type" x-model="type">@foreach(App\Enums\WhatsAppMessageType::cases() as $type)<option value="{{ $type->value }}">{{ str($type->value)->headline() }}</option>@endforeach</select><label class="field-label mt-5" for="body"><span x-text="type==='text'?'Message':'Caption (optional)'"></span></label><textarea class="field mt-2 min-h-36" id="body" name="body" maxlength="4096" :required="!template&&type==='text'">{{ old('body') }}</textarea><div x-show="type!=='text'" class="mt-5"><label class="field-label" for="attachment">Private attachment</label><input class="field mt-2" id="attachment" type="file" name="attachment" :required="!template&&type!=='text'"><p class="mt-1 text-xs text-[var(--text-muted)]">Supported image, PDF/document, audio, or MP4 files up to 16 MB. MIME type is verified server-side.</p></div></div>
  @if($errors->any())<x-alert variant="danger" class="mt-5"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
  <button class="btn-primary mt-6" @disabled($sessions->isEmpty())>Queue transactional message</button>
 </form><aside class="app-card-subtle h-fit p-5"><h2 class="section-title">Responsible use</h2><ul class="muted mt-3 list-disc space-y-2 pl-5"><li>Confirm recipient consent.</li><li>Only one recipient is supported.</li><li>Template previews use fictional data and send nothing.</li><li>Delivery and read states depend on WhatsApp acknowledgements.</li></ul></aside></div>
</x-layouts.app>
