<x-layouts.app title="Message details">
 <div x-data="{state:'{{ $message->status->value }}',label:'{{ $message->status->label() }}',polls:0}" x-init="if(!{{ $message->status->isTerminal()?'true':'false' }}){let timer=setInterval(async()=>{if(document.hidden)return;let r=await fetch('{{ route('tenant.messages.status',$message->uuid) }}',{headers:{Accept:'application/json'}});if(r.ok){let d=await r.json();state=d.status;label=d.label;if(d.terminal||++polls>100)clearInterval(timer)}},3000)}">
 <x-page-header eyebrow="Message details" title="Message to {{ $message->maskedRecipient() }}" description="Transactional delivery state and safe event history."><x-slot:actions><a class="btn-secondary" href="{{ route('tenant.messages.index') }}">Back</a></x-slot:actions></x-page-header>
 <div class="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><section class="space-y-6"><div class="panel" aria-live="polite"><div class="flex items-center justify-between"><h2 class="section-title">Delivery state</h2><x-badge variant="info"><span x-text="label"></span></x-badge></div><dl class="mt-5 grid gap-4 sm:grid-cols-2"><div><dt class="muted">Session</dt><dd class="font-medium">{{ $message->session->name }}</dd></div><div><dt class="muted">Type</dt><dd class="font-medium">{{ $message->message_type->value }}</dd></div><div><dt class="muted">Attempts</dt><dd>{{ $message->attempts }} / {{ $message->max_attempts }}</dd></div><div><dt class="muted">Expires</dt><dd>{{ $message->expires_at?->format('M j, H:i') }}</dd></div></dl>@if($message->failure_message)<x-alert variant="danger" class="mt-5">{{ $message->failure_message }}</x-alert>@endif</div>
 @if($message->body)<div class="panel"><h2 class="section-title">Plain-text content</h2><p class="mt-4 whitespace-pre-wrap text-sm leading-7">{{ $message->body }}</p></div>@endif
 <div class="panel"><h2 class="section-title">Event timeline</h2><ol class="mt-5 space-y-4">@foreach($message->events as $event)<li class="border-l-2 border-[var(--border)] pl-4"><p class="font-medium">{{ str($event->event)->replace('.',' ')->headline() }}</p><p class="muted">{{ $event->to_status ? str($event->to_status)->headline() : $event->source }} · {{ $event->occurred_at->format('M j, H:i:s') }}</p></li>@endforeach</ol></div></section>
 <aside class="space-y-4">@if($message->attachment)<div class="app-card p-5"><h2 class="section-title">Attachment</h2><p class="mt-3 break-all text-sm">{{ $message->attachment->safe_name }}</p><p class="muted mt-1">{{ $message->attachment->mime_type }} · {{ Number::fileSize($message->attachment->size_bytes) }}</p><a class="btn-secondary mt-4 w-full" href="{{ route('tenant.messages.attachment',$message->uuid) }}">Download safely</a></div>@endif
 @if($message->status->canCancel())<form method="post" action="{{ route('tenant.messages.cancel',$message->uuid) }}">@csrf<button class="btn-secondary w-full">Cancel before send</button></form>@endif
 @if($message->status===App\Enums\WhatsAppMessageStatus::Failed && $message->failure_retryable && $message->attempts<$message->max_attempts)<form method="post" action="{{ route('tenant.messages.retry',$message->uuid) }}">@csrf<button class="btn-primary w-full">Retry eligible failure</button></form>@endif
 </aside></div></div>
</x-layouts.app>
