<x-layouts.app :title="isset($template)?'Edit template':'New template'">
@php($version=$template->currentDraftVersion??null) @php($editing=isset($template))
<x-page-header :title="$editing?'Edit '.$template->name:'Create message template'" description="Build safe plain-text content with registered variables."><x-slot:actions>@if($editing)<a class="btn-secondary" href="{{ route('tenant.message-templates.show',$template) }}">View template</a>@endif</x-slot:actions></x-page-header>
@if($errors->any())<x-alert variant="danger" title="Template could not be saved"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></x-alert>@endif
<form class="space-y-5" method="post" action="{{ $editing?route('tenant.message-templates.update',$template):route('tenant.message-templates.store') }}" x-data="{section:1,type:@js(old('type',$template->type->value??'text')),body:@js(old('body',$version->body??'')),caption:@js(old('caption',$version->caption??''))}">@csrf @if($editing)@method('PUT')<input type="hidden" name="expected_version" value="{{ $template->lock_version }}">@endif
<nav class="flex gap-2 overflow-x-auto pb-2" aria-label="Template form sections">@foreach(['Basics','Content','Variables','Media','Organization','Preview'] as $i=>$label)<button type="button" class="btn-secondary shrink-0" :class="section=={{ $i+1 }}&&'ring-2 ring-emerald-500'" @click="section={{ $i+1 }}" :aria-current="section=={{ $i+1 }}?'step':null">{{ $i+1 }}. {{ $label }}</button>@endforeach</nav>
<section x-show="section===1" class="card grid gap-4 md:grid-cols-2"><label>Name<input class="input mt-2" name="name" required maxlength="150" value="{{ old('name',$template->name??'') }}"></label><label>Type<select class="input mt-2" name="type" x-model="type">@foreach(App\Enums\WhatsAppMessageTemplateType::cases() as $type)<option value="{{ $type->value }}">{{ ucfirst($type->value) }}</option>@endforeach</select></label><label class="md:col-span-2">Description<textarea class="input mt-2" name="description" maxlength="1000">{{ old('description',$template->description??'') }}</textarea></label></section>
<section x-show="section===2" class="card space-y-4"><label>Body<textarea class="input mt-2 min-h-44" name="body" x-model="body"></textarea><span class="text-xs text-[var(--text-muted)]" x-text="body.length+' characters'"></span></label><label x-show="type!=='text'">Caption<textarea class="input mt-2 min-h-28" name="caption" x-model="caption"></textarea><span class="text-xs text-[var(--text-muted)]" x-text="caption.length+' characters'"></span></label><p class="text-sm text-[var(--text-muted)]">Insert only registered placeholders such as <code>@{{first_name}}</code>. HTML, expressions, functions, filters, and dot paths are not supported.</p></section>
<section x-show="section===3" class="card"><input type="hidden" name="variable_context" value="contact"><h2 class="font-semibold">Registered variables</h2><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach($variables as $variable)<div class="rounded-xl border p-3"><code>@{{{{ $variable->key }}}}</code><div class="mt-2 flex gap-3 text-sm"><label><input type="checkbox" name="variable_configuration[{{ $variable->key }}][required]" value="1" @checked(data_get($version?->variable_configuration,$variable->key.'.required'))> Required</label><input class="input" name="variable_configuration[{{ $variable->key }}][default]" value="{{ old('variable_configuration.'.$variable->key.'.default',data_get($version?->variable_configuration,$variable->key.'.default')) }}" placeholder="Optional default"></div></div>@endforeach</div></section>
<section x-show="section===4" class="card"><h2 class="font-semibold">Private media</h2><p class="mt-2 text-sm text-[var(--text-muted)]" x-show="type==='text'">Text templates do not require media.</p>@if($editing && $version?->attachment)<dl class="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt>Filename</dt><dd>{{ $version->attachment->safe_name }}</dd></div><div><dt>Detected MIME</dt><dd>{{ $version->attachment->mime_type }}</dd></div><div><dt>Size</dt><dd>{{ number_format($version->attachment->size_bytes/1024,1) }} KB</dd></div><div><dt>Checksum</dt><dd>Verified · {{ substr($version->attachment->checksum_sha256,0,12) }}…</dd></div></dl>@else<p class="mt-3 text-sm">Save the draft first, then upload media from its detail page.</p>@endif</section>
<section x-show="section===5" class="card"><p class="text-sm">Category and labels can be assigned from the template detail page after saving.</p></section>
<section x-show="section===6" class="card grid gap-5 lg:grid-cols-2"><div><h2 class="font-semibold">Fictional preview</h2><p class="text-sm text-[var(--text-muted)]">Preview data is fictional and no message is sent.</p><button type="button" class="btn-secondary mt-4" @click="fetch('{{ $editing?route('tenant.message-templates.preview',$template):'#' }}',{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.content||'',Accept:'application/json','Content-Type':'application/json'},body:'{}'}).then(r=>r.json()).then(x=>$refs.preview.textContent=x.body||x.caption||'No preview').catch(()=>$refs.preview.textContent='Save the draft before previewing.')">Preview saved draft</button></div><div class="rounded-2xl bg-slate-900 p-5 text-white"><p x-ref="preview" class="whitespace-pre-wrap" x-text="body||caption||'Preview appears here.'"></p></div></section>
<div class="sticky bottom-4 flex justify-end"><button class="btn-primary">{{ $editing?'Save draft':'Create draft' }}</button></div></form>
</x-layouts.app>
