<?php

return [
    'super_admin_role' => 'super-admin',
    'permissions' => [
        'platform.dashboard.view' => 'View platform dashboard',
        'platform.tenants.view' => 'View tenants',
        'platform.tenants.manage' => 'Suspend and reactivate tenants',
        'platform.users.view' => 'View users',
        'platform.users.manage' => 'Suspend and reactivate users',
        'platform.notes.manage' => 'Add internal platform notes',
        'platform.audit.view' => 'View platform audit events',
        'platform.queues.view' => 'View queue operations',
        'platform.queues.manage' => 'Retry and delete failed jobs',
        'platform.health.view' => 'View system health',
        'platform.roles.manage' => 'Manage platform role assignments',
        'platform.plans.view' => 'View subscription plans',
        'platform.plans.manage' => 'Manage subscription plans',
        'platform.subscriptions.view' => 'View tenant subscriptions',
        'platform.subscriptions.manage' => 'Manage tenant subscriptions',
        'platform.whatsapp.view' => 'View WhatsApp session operations',
        'platform.whatsapp.manage' => 'Queue WhatsApp session recovery',
        'platform.messages.view' => 'View outbound message operations',
        'platform.messages.manage' => 'Reconcile outbound messages',
        'platform.contacts.view' => 'View redacted contact operations',
        'platform.contact_imports.view' => 'View contact import operations',
        'platform.contact_segments.view' => 'View contact segment operations',
        'platform.campaigns.view' => 'View campaign operations',
        'platform.campaigns.view_details' => 'View redacted campaign details',
        'platform.campaigns.manage_operations' => 'Manage campaign operations',
        'platform.campaign_executions.view' => 'View campaign executions',
        'platform.campaign_executions.reconcile' => 'Reconcile campaign executions',
        'platform.whatsapp_templates.view' => 'View message templates',
        'platform.whatsapp_templates.view_versions' => 'View message template versions',
        'platform.automations.view' => 'View automation workflows',
        'platform.automations.view_versions' => 'View automation workflow versions',
        'platform.automation_executions.view' => 'View automation workflow executions',
        'platform.inbox.view' => 'View shared inbox operations',
        'platform.inbox.view_messages' => 'View safe shared inbox message summaries',
        'platform.inbox.view_failures' => 'View shared inbox failures',
        'platform.analytics.view' => 'View platform analytics',
        'platform.chatbots.view' => 'View rule-based chatbots',
        'platform.integrations.view' => 'View integrations',
    ],
    'roles' => [
        'super-admin' => ['name' => 'Super Admin', 'permissions' => ['*']],
        'operations' => ['name' => 'Operations', 'permissions' => [
            'platform.dashboard.view', 'platform.tenants.view', 'platform.tenants.manage',
            'platform.users.view', 'platform.notes.manage', 'platform.audit.view',
            'platform.queues.view', 'platform.queues.manage', 'platform.health.view',
            'platform.plans.view', 'platform.plans.manage', 'platform.subscriptions.view', 'platform.subscriptions.manage',
            'platform.whatsapp.view', 'platform.whatsapp.manage',
            'platform.messages.view', 'platform.messages.manage',
            'platform.contacts.view', 'platform.contact_imports.view', 'platform.contact_segments.view',
            'platform.campaigns.view', 'platform.campaigns.view_details',
            'platform.campaign_executions.view',
            'platform.whatsapp_templates.view', 'platform.whatsapp_templates.view_versions',
            'platform.automation_executions.view',
            'platform.inbox.view', 'platform.inbox.view_messages', 'platform.inbox.view_failures',
            'platform.analytics.view', 'platform.chatbots.view', 'platform.integrations.view',
        ]],
        'support' => ['name' => 'Support', 'permissions' => [
            'platform.dashboard.view', 'platform.tenants.view', 'platform.users.view',
            'platform.notes.manage', 'platform.audit.view', 'platform.health.view',
            'platform.plans.view', 'platform.subscriptions.view',
            'platform.whatsapp.view',
            'platform.messages.view',
            'platform.contacts.view', 'platform.contact_imports.view', 'platform.contact_segments.view',
            'platform.campaigns.view', 'platform.campaigns.view_details',
            'platform.campaign_executions.view',
            'platform.whatsapp_templates.view', 'platform.whatsapp_templates.view_versions',
            'platform.automation_executions.view',
            'platform.inbox.view', 'platform.inbox.view_messages', 'platform.inbox.view_failures',
            'platform.analytics.view', 'platform.chatbots.view', 'platform.integrations.view',
        ]],
        'auditor' => ['name' => 'Auditor', 'permissions' => [
            'platform.dashboard.view', 'platform.tenants.view', 'platform.users.view',
            'platform.audit.view', 'platform.queues.view', 'platform.health.view',
            'platform.plans.view', 'platform.subscriptions.view',
            'platform.whatsapp.view',
            'platform.messages.view',
            'platform.contacts.view', 'platform.contact_imports.view', 'platform.contact_segments.view',
            'platform.campaigns.view', 'platform.campaigns.view_details',
            'platform.campaign_executions.view',
            'platform.whatsapp_templates.view', 'platform.whatsapp_templates.view_versions',
            'platform.automation_executions.view',
            'platform.inbox.view', 'platform.inbox.view_messages', 'platform.inbox.view_failures',
            'platform.analytics.view', 'platform.chatbots.view', 'platform.integrations.view',
        ]],
    ],
];
