<?php

return [
    'default_plan_slug' => env('SUBSCRIPTION_DEFAULT_PLAN_SLUG', 'trial'),
    'default_trial_days' => (int) env('SUBSCRIPTION_DEFAULT_TRIAL_DAYS', 14),
    'grace_allows_access' => true,
    'warning_threshold' => 80,
    'features' => [
        'dashboard.access' => 'Workspace dashboard',
        'team.manage' => 'Team management',
        'roles.manage' => 'Custom role management',
        'audit_logs.view' => 'Audit log access',
        'whatsapp.sessions' => 'WhatsApp sessions',
        'messages.send' => 'Message sending',
        'contacts.manage' => 'Contact management',
        'campaigns.manage' => 'Campaign management',
        'campaigns.schedule' => 'Campaign scheduling',
        'whatsapp_message_templates' => 'WhatsApp message templates',
        'automations.access' => 'Automation workflows',
        'inbox.access' => 'Shared inbox',
        'analytics.access' => 'Analytics and reporting',
        'chatbots.access' => 'Rule-based chatbots',
        'integrations.access' => 'External integrations',
        'api_keys.manage' => 'API key management',
        'webhooks.manage' => 'Webhook management',
        'priority_support' => 'Priority support',
    ],
    'limits' => [
        'team_members.max' => 'Active team members',
        'pending_invitations.max' => 'Pending invitations',
        'roles.custom.max' => 'Custom roles',
        'whatsapp_sessions.max' => 'WhatsApp sessions',
        'contacts.max' => 'Contacts',
        'contact_groups.max' => 'Contact groups',
        'contact_labels.max' => 'Contact labels',
        'contact_segments.max' => 'Saved contact segments',
        'campaigns.max' => 'Campaigns',
        'campaigns.active_max' => 'Active campaigns',
        'campaigns.monthly_max' => 'Monthly launched campaigns',
        'campaigns.recipients_per_campaign_max' => 'Recipients per campaign',
        'campaigns.manual_contacts_max' => 'Manual contacts per campaign',
        'campaigns.sessions_per_campaign_max' => 'Sessions per campaign',
        'whatsapp_message_templates.max' => 'Message templates',
        'whatsapp_message_templates.published_max' => 'Published message templates',
        'automations.max' => 'Active automation workflows',
        'chatbots.max' => 'Chatbots',
        'integrations.max' => 'Integrations',
        'api_keys.max' => 'API keys',
        'webhooks.max' => 'Webhooks',
        'messages.monthly' => 'Monthly messages',
    ],
];
