<x-layouts.platform :title="$plan->exists?'Edit plan':'Create plan'">
 <x-page-header eyebrow="Commercial configuration" :title="$plan->exists?'Edit '.$plan->name:'Create subscription plan'" description="Define entitlements only. Payment collection is not part of this console." />
 <form method="post" action="{{ $plan->exists?route('platform.plans.update',$plan):route('platform.plans.store') }}" class="mt-6 space-y-6">@csrf @if($plan->exists)@method('put')@endif
 <section class="panel"><h2 class="section-title">Plan identity</h2><div class="mt-4 grid gap-4 md:grid-cols-2"><x-input label="Name" name="name" :value="old('name',$plan->name)" required/><x-input label="Slug" name="slug" :value="old('slug',$plan->slug)" /><div class="md:col-span-2"><label class="text-sm font-semibold" for="description">Description</label><textarea id="description" name="description" class="field mt-2" maxlength="1000" rows="3">{{ old('description',$plan->description) }}</textarea></div><label class="text-sm">Status<select class="field mt-2" name="status">@foreach(['draft','active','archived'] as $v)<option value="{{ $v }}" @selected(old('status',$plan->status?->value??'draft')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></label><label class="text-sm">Billing interval<select class="field mt-2" name="billing_interval">@foreach(['monthly','yearly'] as $v)<option value="{{ $v }}" @selected(old('billing_interval',$plan->billing_interval?->value??'monthly')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></label><x-input label="Price (minor units)" name="price_amount" type="number" min="0" :value="old('price_amount',$plan->price_amount)"/><x-input label="Currency" name="price_currency" maxlength="3" :value="old('price_currency',$plan->price_currency??'USD')"/><x-input label="Trial days" name="trial_days" type="number" min="0" :value="old('trial_days',$plan->trial_days??0)"/><x-input label="Grace days" name="grace_days" type="number" min="0" :value="old('grace_days',$plan->grace_days??0)"/></div><div class="mt-4 flex gap-5"><label><input type="checkbox" name="is_public" value="1" @checked(old('is_public',$plan->is_public))> Public</label><label><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$plan->is_featured))> Featured</label></div></section>
 @php($map=$plan->features->keyBy('feature_key'))
 <section class="panel"><h2 class="section-title">Feature access</h2><div class="mt-4 grid gap-3 md:grid-cols-2">@foreach(config('subscriptions.features') as $key=>$label)<label class="app-card-subtle flex gap-3 p-3"><input type="checkbox" name="features[]" value="{{ $key }}" @checked(old('features')?in_array($key,old('features'),true):($map->get($key)?->boolean_value??false))><span><b class="block text-sm">{{ $label }}</b><small class="text-[var(--text-muted)]">{{ $key }}</small></span></label>@endforeach</div></section>
 <section class="panel"><h2 class="section-title">Resource limits</h2><div class="mt-4 grid gap-4 md:grid-cols-2">@foreach(config('subscriptions.limits') as $key=>$label)@php($feature=$map->get($key))<div class="app-card-subtle p-4"><label class="text-sm font-semibold">{{ $label }}<input class="field mt-2" type="number" min="0" name="limits[{{ $key }}]" value="{{ old('limits.'.$key,$feature?->integer_value??0) }}"></label><label class="mt-2 block text-sm"><input type="checkbox" name="limit_unlimited[{{ $key }}]" value="1" @checked(old('limit_unlimited.'.$key,$feature?->is_unlimited??false))> Unlimited</label><small class="text-[var(--text-muted)]">{{ $key }}</small></div>@endforeach</div></section>
 <div class="flex justify-end gap-3"><a class="btn-secondary" href="{{ route('platform.plans.index') }}">Cancel</a><button class="btn-primary">Save plan</button></div></form>
</x-layouts.platform>
