<x-layouts.platform :title="$tenant->name.' billing'">
    <x-page-header eyebrow="Tenant billing" :title="$tenant->name" description="Manual subscription administration and payment history."><x-slot:actions><a class="btn-secondary" href="{{ route('platform.billing.index') }}">Back to billing</a></x-slot:actions></x-page-header>
    @php($subscription=$tenant->currentSubscription)
    <section class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article class="panel"><p class="muted">Plan</p><p class="mt-2 font-semibold">{{ $subscription?->plan?->name ?? 'Unassigned' }}</p></article><article class="panel"><p class="muted">Status</p><p class="mt-2 font-semibold">{{ $subscription ? str($subscription->status->value)->headline() : 'Missing' }}</p></article><article class="panel"><p class="muted">Period end</p><p class="mt-2 font-semibold">{{ $subscription?->current_period_ends_at?->format('M j, Y') ?? 'Open ended' }}</p></article><article class="panel"><p class="muted">Messages</p><p class="mt-2 font-semibold">{{ number_format($messageUsage['usage']) }} / {{ $messageUsage['unlimited'] ? 'Unlimited' : number_format($messageUsage['limit']) }}</p></article></section>
    <div class="mt-6 grid gap-6 xl:grid-cols-2">
        <section class="panel"><h2 class="section-title">Assign or change plan</h2><form method="post" action="{{ route('platform.tenants.subscription.assign',$tenant) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf<label class="text-sm">Plan<select class="field mt-2" name="plan_uuid" required>@foreach($plans as $plan)<option value="{{ $plan->uuid }}">{{ $plan->name }}</option>@endforeach</select></label><x-input label="Trial days" name="trial_days" type="number" min="0" value="0"/><x-input label="Start date" name="starts_at" type="date" :value="now()->toDateString()"/><x-input label="Period end" name="period_ends_at" type="date"/><div class="sm:col-span-2"><x-input label="Administrative reason" name="reason" required maxlength="500"/></div><button class="btn-primary w-fit">Assign plan</button></form></section>
        @if($subscription)<section class="panel"><h2 class="section-title">Lifecycle</h2><form method="post" action="{{ route('platform.tenants.subscription.status',$tenant) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf<label class="text-sm">New status<select class="field mt-2" name="status" required><option value="">Choose status</option>@foreach($allowedSubscriptionStatuses as $status)<option value="{{ $status }}">{{ ucfirst($status) }}</option>@endforeach</select></label><x-input label="Reason" name="reason" required maxlength="500"/><button class="btn-secondary w-fit">Update status</button></form>@error('status')<p class="mt-2 text-sm text-[var(--danger)]">{{ $message }}</p>@enderror<form method="post" action="{{ route('platform.tenants.subscription.extend',$tenant) }}" class="mt-6 grid gap-4 sm:grid-cols-2">@csrf<x-input label="New period end" name="period_ends_at" type="date" required/><x-input label="Extension reason" name="reason" required maxlength="500"/><button class="btn-secondary w-fit">Extend subscription</button></form></section>@endif
        <section class="panel"><h2 class="section-title">Record manual payment</h2><form method="post" action="{{ route('platform.tenants.billing.payments.store',$tenant) }}" class="mt-4 grid gap-4 sm:grid-cols-2">@csrf<x-input label="Amount (minor units)" name="amount" type="number" min="0" required/><x-input label="Currency" name="currency" value="{{ $tenant->currency ?: 'USD' }}" maxlength="3" required/><x-input label="Paid date" name="paid_at" type="date" :value="now()->toDateString()" required/><x-input label="Reference" name="reference" maxlength="120"/><div class="sm:col-span-2"><x-input label="Safe administrative note" name="notes" maxlength="1000"/></div><button class="btn-primary w-fit">Record payment</button></form></section>
        <section class="panel"><h2 class="section-title">Recent payments</h2><div class="mt-4 overflow-x-auto"><table class="data-table"><thead><tr><th>Date</th><th>Amount</th><th>Reference</th><th>Recorded by</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->paid_at?->format('M j, Y') }}</td><td>{{ $payment->currency }} {{ number_format($payment->amount / 100, 2) }}</td><td>{{ $payment->reference ?: '—' }}</td><td>{{ $payment->recorder?->name ?? 'System' }}</td></tr>@empty<tr><td colspan="4">No payments recorded.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $payments->links() }}</div></section>
    </div>
</x-layouts.platform>
